// Ask a Mahjong Rule: the only place rule text may come from. Retrieval picks an entry
// and the optional model may rephrase one, but nothing may add rule content that is not
// written here. Annual NMJL card hands are copyrighted and must never appear in this file;
// lib/ask/engine.ts refuses those questions before retrieval.
//
// Sources, in order of authority:
//   shared_approved  verbatim copy of an owner-approved entry from Find My Mahj
//                    (findmymahjgame/lib/rules/knowledge.ts). Same id, same text. A test
//                    compares the two files whenever the sister repo is checked out beside
//                    this one, so the two sites cannot drift apart silently.
//   lvm_rules_page   verbatim text from a lasvegasmahj.com/rules page (source_url).
//   owner_approved   approved by the owner on 2026-08-29 without a matching /rules Q&A yet.
//   derived          composed only from approved statements above, but the exact wording
//                    has not yet been reviewed by the instructor. The UI labels these
//                    "Pending instructor review" until the owner flips the source.

import { pageAnswer } from "@/content/rules";

export const CURRENT_CARD_YEAR = 2026;

export type AskCategory =
  | "tiles"
  | "jokers"
  | "charleston"
  | "calling"
  | "winning"
  | "scoring"
  | "dead-hands"
  | "card"
  | "etiquette"
  | "basics";

export type AskSource = "shared_approved" | "lvm_rules_page" | "owner_approved" | "derived";

export type AskLevel = "foundational" | "core" | "advanced";

export type KnowledgeEntry = {
  id: string;
  category: AskCategory;
  level: AskLevel;
  question: string;
  patterns: RegExp[];
  generic?: RegExp[];
  keywords: string[];
  answer: string;
  varies_by_house: boolean;
  house_note?: string;
  confidence: "high" | "medium";
  source: AskSource;
  // Set only when the linked /rules page agrees with the answer; a link would otherwise send
  // the player straight to the opposite wording. Restore it when the page is corrected.
  source_url?: string;
  // The /rules Q&A this entry mirrors ("slug.id"). A mirrored entry reads its answer from the
  // page module, so the two cannot drift; tests/rules-truth.logic.spec.ts enforces it.
  page_ref?: string[];
  related: string[];
};

const RULES = "https://www.lasvegasmahj.com/rules";

export const RULES_KNOWLEDGE: KnowledgeEntry[] = [
  // ── Shared, owner-approved (verbatim from Find My Mahj) ──────────────────────
  {
    id: "tile-count",
    category: "tiles",
    level: "foundational",
    question: "How many tiles are in an American Mahjong set?",
    patterns: [
      /how many tile/,
      /tile (are|come|in) (a|an|the) (american )?(mahjong )?set/,
      /\b152\b/,
      /tile count/,
      /what('s| is) in (a|an|the) (american )?(mahjong )?set/,
      /how many (joker|flower|dragon|wind)/,
    ],
    keywords: ["152", "set", "how many"],
    answer:
      "An American mahjong set has 152 tiles: the three suits (Bams, Craks, and Dots) numbered 1 through 9 with 4 copies of each tile, 16 winds, 12 dragons, 8 flowers, and 8 jokers.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["suits", "jokers-basics", "the-wall"],
  },
  {
    id: "suits",
    category: "tiles",
    level: "foundational",
    question: "What are the three suits?",
    patterns: [/what (are|'re) the (three |3 )?suit/, /(three|3) suit/, /suit (in|of) (american )?mahjong/, /how many suit/, /\b(bam|crak|dot)\b.{0,30}\bsuit/, /\bsuit\b.{0,30}\b(bam|crak|dot)\b/, /name the suit/, /which suit/],
    generic: [/\bsuit\b/],
    keywords: ["suit", "bam", "crak", "dot"],
    answer:
      "American mahjong uses three suits: Bams, Craks, and Dots. Each suit runs from 1 to 9, and the set holds 4 copies of every suit tile.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["dragons", "tile-count", "winds"],
  },
  {
    id: "dragons",
    category: "tiles",
    level: "foundational",
    question: "Which dragon goes with which suit?",
    patterns: [/which dragon (goes|matches|belongs)/, /\bdragon\b.{0,30}\b(suit|bam|crak|dot|match|belong|go with)/, /\b(suit|bam|crak|dot)\b.{0,30}\bdragon\b/, /(red|green|soap) dragon/],
    generic: [/\bdragon\b/, /\bsoap\b/],
    keywords: ["dragon", "soap", "red", "green", "white"],
    answer:
      "American mahjong has three dragons, and each one belongs to a suit: the Red dragon goes with Craks, the Green dragon goes with Bams, and the White dragon, called the Soap, goes with Dots. The set holds 4 of each dragon, 12 dragon tiles in all.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["suits", "flowers", "winds"],
  },
  {
    id: "flowers",
    category: "tiles",
    level: "foundational",
    question: "Are flowers interchangeable?",
    patterns: [/are flower (numbered|interchangeable|the same)/, /flower.{0,30}(interchangeable|numbered|same|any|different|match)/],
    generic: [/\bflower\b/],
    keywords: ["flower"],
    answer:
      "Flowers are all interchangeable, and they are not numbered. Any flower can stand in for any other flower; a flower is a flower is a flower. An American set has 8 of them.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["dragons", "jokers-basics", "tile-count"],
  },
  {
    id: "winds",
    category: "tiles",
    level: "foundational",
    question: "How do the winds work?",
    patterns: [/north.{0,10}east.{0,10}west.{0,10}south/, /how (do|does).{0,10}wind/, /wind.{0,20}(suit|work|belong)/],
    generic: [/\bwind\b/],
    keywords: ["wind", "north", "south", "east", "west"],
    answer:
      "An American set includes 4 winds: North, East, West, and South, with 4 copies of each for 16 wind tiles in total. Winds do not belong to any suit.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["joker-in-news", "dragons", "dealing"],
  },
  {
    id: "jokers-basics",
    category: "jokers",
    level: "foundational",
    question: "How do jokers work?",
    patterns: [/what (is|are) (a )?joker/, /how (do|does) (a )?joker work/, /joker (wild|rule)/, /\bwild tile/, /\babout joker\b/, /^joker$/, /\bjoker\b.{0,30}\b(pung|kong|quint|sextet|group|set)\b/, /\b(pung|kong|quint|sextet|group|set)\b.{0,30}\bjoker\b/],
    keywords: ["joker", "wild", "kong", "pung", "quint", "sextet"],
    answer:
      "Jokers are wild tiles, and they are unique to American mahjong. A joker can stand in for any tile inside a group of 3 or more, meaning a Pung, Kong, Quint, or Sextet. An American set has 8 jokers.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-exchange", "joker-substitute"],
  },
  {
    id: "joker-in-pair",
    category: "jokers",
    level: "core",
    question: "Can I use a joker in a pair?",
    patterns: [/\bjoker\b.{0,60}\bpair\b/, /\bpair\b.{0,60}\bjoker\b/],
    keywords: ["joker", "pair", "single"],
    answer:
      "No. A joker can never be used in a pair or as a single tile. Jokers only work inside groups of 3 or more: a Pung, Kong, Quint, or Sextet. Hands built entirely from singles and pairs take no jokers at all.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/jokers`,
    related: ["joker-substitute", "joker-exchange", "joker-in-news"],
  },
  {
    id: "joker-exchange",
    category: "jokers",
    level: "core",
    question: "When can I exchange a joker?",
    patterns: [/\bexchange\b.{0,30}\bjoker\b/, /\bjoker\b.{0,30}\bexchange\b/, /take.{0,20}\bjoker\b.{0,30}(expose|rack)/, /\bjoker\b.{0,40}\b(another|other|someone|somebody)('s)? (player|expose|set)/],
    keywords: ["joker", "exchange", "expose"],
    answer:
      "Yes, joker exchange is allowed. When any player has an exposed group on the table that contains a joker, you may, on your own turn, hand over the real tile that joker stands for and take the joker into your hand. You can only redeem a joker from an exposure, never from tiles hidden in another player's hand.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "discarded-joker", "joker-free"],
  },
  {
    id: "dealing",
    category: "basics",
    level: "foundational",
    question: "How many tiles does each player start with?",
    patterns: [/how many tile.{0,40}(start|deal|dealt|hand)/, /\bstart with\b/, /who (start|deal|goes first|is east)/, /\b(13|14) tile/, /\bdealer\b/, /\beast\b.{0,20}\b(14|first|discard)/],
    keywords: ["deal", "dealer", "start", "east", "first"],
    answer:
      "Each player starts with 13 tiles, except East, the dealer, who starts with 14. After the Charleston, East opens play by discarding a tile.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/winning`,
    related: ["the-wall", "charleston", "players-count"],
  },
  {
    id: "charleston",
    category: "charleston",
    level: "foundational",
    question: "How does the Charleston work?",
    patterns: [/(how|what).{0,20}charleston.{0,10}(work|is|go|mean)/, /what is (the |a )?charleston/, /\bpass\b.{0,20}\btile\b/, /\bjoker\b.{0,30}\bpass\b/, /\bpass\b.{0,30}\bjoker\b/],
    generic: [/\bcharleston\b/],
    keywords: ["charleston", "pass", "blind", "second"],
    answer:
      "The Charleston is the tile passing that happens before play begins. In the first Charleston, every player passes 3 tiles right, then 3 across, then 3 left; this first round is required. If all four players agree, a second Charleston follows: 3 left, 3 across, 3 right. On the last pass of each Charleston you may pass blind, taking tiles from the pass coming to you without looking at them. Afterward, you and the player across from you may make an optional courtesy pass of up to 3 tiles. You may never pass a joker in the Charleston.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/charleston`,
    related: ["charleston-passes", "charleston-blind-pass", "call-during-charleston"],
  },
  {
    id: "stop-charleston",
    category: "charleston",
    level: "core",
    question: "Can I stop the Charleston?",
    patterns: [/\bstop\b.{0,30}\bcharleston\b/, /\bcharleston\b.{0,30}\b(stop|skip|refuse|optional|required|mandatory|compulsory)\b/, /(skip|refuse|decline).{0,20}(second|2nd) charleston/, /(do|does) (i|we|everyone) have to.{0,20}charleston/],
    keywords: ["charleston", "stop", "skip", "second", "optional"],
    answer: pageAnswer("charleston.stop"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    page_ref: ["charleston.stop"],
    related: ["charleston-passes", "courtesy-pass", "charleston"],
  },
  {
    id: "charleston-jokers",
    category: "charleston",
    level: "core",
    question: "Can I pass a joker in the Charleston?",
    patterns: [/\bpass\b.{0,20}\bjoker\b/, /\bjoker\b.{0,20}\bpass\b/, /\bjoker\b.{0,30}\bcharleston\b/, /\bcharleston\b.{0,30}\bjoker\b/, /(have|need|required) to pass.{0,10}joker/],
    keywords: ["joker", "pass", "charleston"],
    answer: pageAnswer("charleston.pass-jokers"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    page_ref: ["charleston.pass-jokers"],
    related: ["charleston", "charleston-blind-pass", "stop-charleston"],
  },
  {
    id: "charleston-blind-pass",
    category: "charleston",
    level: "core",
    question: "What is a blind pass?",
    patterns: [/blind pass/, /\bblind\b.{0,20}\bpass\b/, /\bpass\b.{0,20}\bblind\b/, /pass.{0,30}without look/],
    keywords: ["blind", "pass", "charleston"],
    answer:
      "A blind pass is allowed only on the last pass of each Charleston: First Left and, if a second Charleston is played, Last Right. If you do not want to pass three tiles from your own hand, you may take one, two, or all three tiles being passed to you and pass them onward without looking at them. You still pass three tiles total. A blind pass does not override the rule against passing jokers. Do not knowingly include a joker from your own hand. Tiles you pass on blindly must remain unseen.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/charleston`,
    page_ref: ["charleston.blind-pass"],
    related: ["charleston-passes", "look-before-pass", "courtesy-pass"],
  },
  {
    id: "open-vs-closed",
    category: "card",
    level: "core",
    question: "What is the difference between an open and a closed hand?",
    patterns: [/\b(open|closed|concealed)\b.{0,20}\bhand\b/, /\bhand\b.{0,20}\b(open|closed|concealed)\b/, /what does concealed mean/, /difference between open and closed/],
    keywords: ["open", "closed", "concealed", "hand"],
    answer:
      "Open hands can call discards to build exposed groups. Closed hands, also called concealed hands, must be built from your own draws, with no calling to build groups; the only discard a closed hand may claim is the single tile that completes your mahjong.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/the-card`,
    related: ["closed-hand-final-tile", "calling-discard", "call-concealed"],
  },
  {
    id: "closed-hand-final-tile",
    category: "card",
    level: "advanced",
    question: "Can a closed hand call its final tile?",
    patterns: [/\b(closed|concealed)\b.{0,30}\b(call|pick up|take)\b/, /\b(call|pick up|take)\b.{0,30}\b(closed|concealed)\b/, /\b(closed|concealed)\b.{0,45}\b(discard|mahjong)\b/, /\b(closed|concealed)\b.{0,40}\b(final|last|win) tile\b/, /\b(final|last) tile\b.{0,40}\b(mahjong|win|closed|concealed)\b/],
    keywords: ["closed", "concealed", "final", "last", "call"],
    answer:
      "A closed (concealed) hand may not call any discard to build a group. The one exception: you may claim a discard when it is the single tile that completes your mahjong.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/the-card`,
    page_ref: ["the-card.open-closed"],
    related: ["open-vs-closed", "call-for-mahjong", "calling-discard"],
  },
  {
    id: "calling-discard",
    category: "calling",
    level: "core",
    question: "When can I call a discard?",
    patterns: [/\bcall\b.{0,20}\b(discard|tile)\b/, /when can (i|you) call/, /(pick up|take(?! back)).{0,20}\b(discard|thrown tile)\b/, /how (do|does)( i| you| we)? call\b/, /what (is|does) (a |the )?call(ing)?\b/, /\bcall rule\b/, /^can (i|you|we) call$/],
    generic: [/\bdiscard\b/],
    keywords: ["call", "discard"],
    answer:
      "You may call the most recent discard when you can use it right away in an exposed group of 3 or more identical tiles, with jokers allowed to fill in, or when it completes your mahjong. When you call for a group, you must place that group face up on your rack. A call for mahjong beats a call for an exposure.",
    varies_by_house: true,
    house_note:
      "The card closes the calling window once the player next in turn has picked and racked, or discarded; some tables police that moment loosely, so confirm your table follows the card.",
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/calling-tiles`,
    related: ["same-tile-two-calls", "call-for-pair", "call-window"],
  },
  {
    id: "winning-mahjong",
    category: "winning",
    level: "foundational",
    question: "How do you win a hand?",
    patterns: [/how (do|does) (i|you|someone|a player) win/, /what (is|does) mahjong( mean)?/, /declar(e|ing) mahjong/, /\bwin hand\b/, /what counts as (a win|mahjong)/, /how (many|much) tile.{0,20}(win|mahjong)/],
    keywords: ["win", "declare", "mahjong", "14"],
    answer:
      "You win by completing a 14 tile hand that exactly matches one of the hands printed on the current National Mah Jongg League card, then declaring mahjong. The 14th tile can come from your own draw or from a called discard.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/winning`,
    related: ["valid-mahjong", "false-mahjong", "self-drawn-win"],
  },
  {
    id: "annual-card",
    category: "card",
    level: "foundational",
    question: "When does the new card come out?",
    patterns: [/(new|annual|yearly|current|next).{0,15}\bcard\b/, /\bcard\b.{0,25}(come(s)? out|release|publish)/, /when.{0,30}\bcard\b/, /what is the (nmjl |league )?card/, /\bcard\b.{0,20}\b(change|every year|each year)/],
    keywords: ["card", "nmjl", "league", "year"],
    answer:
      "The National Mah Jongg League publishes a new official card every spring. The card lists the hands you can win with, and those hands change every year, so players buy the new card each season directly from the League.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/the-card`,
    related: ["last-years-card", "card-numbers", "winning-mahjong"],
  },
  {
    id: "the-wall",
    category: "basics",
    level: "foundational",
    question: "How is the wall built?",
    patterns: [/build(ing)? the wall/, /how (is|are) the (tile|wall) (set|built|arranged)/, /how (long|tall|big|many).{0,20}wall(?! game)/, /what is (the |a )?wall(?! game)/],
    generic: [/\bwall\b(?! game)/],
    keywords: ["wall", "build"],
    answer:
      "After all 152 tiles are shuffled face down, each player builds a wall 19 tiles long and 2 tiles high. The four walls together hold the whole set, and every deal and draw comes from the wall.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["dealing", "wall-game", "tile-count"],
  },
  {
    id: "wall-game",
    category: "winning",
    level: "core",
    question: "What is a wall game?",
    patterns: [/wall game/, /(nobody|no one) (win|declared)/, /run(s|ning)? out of tile/, /end(s)? in a (draw|tie)/],
    keywords: ["wall game", "draw", "no winner", "nobody"],
    answer:
      "If the wall runs out of tiles before anyone declares mahjong, the hand ends with no winner. This is called a wall game, and no one scores it.",
    varies_by_house: true,
    house_note: "Tables differ on whether the same dealer deals again after a wall game.",
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/winning`,
    related: ["wall-game-payment", "the-wall", "winning-mahjong"],
  },
  {
    id: "players-count",
    category: "basics",
    level: "foundational",
    question: "How many players do you need?",
    patterns: [/how many (player|people)/, /play with (three|3|five|5|two|2)/, /number of player/, /\b(three|3) (player|people)\b/],
    keywords: ["player", "how many", "four", "three"],
    answer:
      "American mahjong is built for 4 players. Many groups adapt it when only 3 can play, but the standard game seats 4.",
    varies_by_house: true,
    house_note: "Adaptations for 3 players vary from table to table; agree on the format before you start.",
    confidence: "high",
    source: "shared_approved",
    related: ["dealing", "the-wall", "tile-count"],
  },
  {
    id: "courtesies-vs-rules",
    category: "etiquette",
    level: "core",
    question: "What is the difference between a rule and a house rule?",
    patterns: [/(table|house) rule/, /\bcourtes(y|ies)\b(?! pass)/, /\betiquette\b/, /rule (vs|versus|or) (courtes|custom)/, /official rule/],
    keywords: ["etiquette", "courtesy", "house", "official"],
    answer:
      "It helps to separate official rules from table courtesies. Official rules come from the National Mah Jongg League and apply everywhere, such as the tile count, how calling works, and the courtesy pass, which is an optional League rule any player may decline. Courtesies are local customs a table agrees on, such as how a wall game is paid or whether the same dealer deals again. Agree on courtesies before the first hand so no one is surprised.",
    varies_by_house: true,
    house_note: "Courtesies differ from table to table by design.",
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/etiquette`,
    related: ["house-vs-nmjl", "table-talk", "disputes"],
  },
  {
    id: "dead-hand",
    category: "dead-hands",
    level: "advanced",
    question: "What is a dead hand?",
    patterns: [/what is (a )?dead hand/, /declar(e|ed|ing) (a hand |someone )?dead/, /dead hand.{0,10}(mean|rule)/],
    generic: [/dead hand/, /hand (is |goes )?dead/, /\bdead\b/],
    keywords: ["dead"],
    answer:
      "A hand is dead when it can no longer win, for example when a player holds the wrong number of tiles or has exposures that cannot fit any hand on the card. A dead player stops drawing and discarding for the rest of that hand. Calling another player's hand dead is a formal challenge, so be sure you are right before you make it.",
    varies_by_house: true,
    house_note: "Tables enforce dead hand challenges with different levels of strictness.",
    confidence: "medium",
    source: "shared_approved",
    source_url: `${RULES}/dead-hands`,
    related: ["called-dead", "dead-hand-triggers", "dead-hand-pays"],
  },

  // ── Las Vegas Mahjong rules pages (verbatim) ─────────────────────────────────
  {
    id: "joker-substitute",
    category: "jokers",
    level: "core",
    question: "What tiles can jokers substitute for?",
    patterns: [/\bjoker\b.{0,30}\b(substitute|stand in|replace|use[sd]? (for|as|in))/, /what can (a )?joker/, /\bjoker\b.{0,20}\b(kong|pung|quint)\b/, /\b(kong|pung|quint)\b.{0,20}\bjoker\b/],
    keywords: ["joker", "substitute", "kong", "pung", "quint"],
    answer: pageAnswer("jokers.substitute"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["jokers.substitute"],
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-exchange", "joker-call-complete"],
  },
  {
    id: "joker-single",
    category: "jokers",
    level: "core",
    question: "Can a joker be used as a single tile?",
    patterns: [/\bjoker\b.{0,30}\bsingle\b/, /\bsingle\b.{0,30}\bjoker\b/, /\b(as|for|in) a single\b/, /single tile/],
    keywords: ["joker", "single", "slot"],
    answer: pageAnswer("jokers.single"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["jokers.single"],
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-in-news", "joker-substitute"],
  },
  {
    id: "joker-singles-pairs-hand",
    category: "jokers",
    level: "core",
    question: "Can I use a joker in a Singles and Pairs hand?",
    patterns: [/single.{0,5}(and|&).{0,5}pair/, /singles? pair/, /\bjoker\b.{0,40}single.{0,5}(and|&).{0,5}pair/],
    keywords: ["single", "pair", "joker"],
    answer: pageAnswer("jokers.singles-pairs-hand"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["jokers.singles-pairs-hand"],
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-free", "joker-single"],
  },
  {
    id: "joker-free",
    category: "scoring",
    level: "advanced",
    question: "What is a joker-free hand and what does it pay?",
    patterns: [/joker free/, /\b(no|zero|without) joker/, /\bjoker\b.{0,20}\b(bonus|double|extra)\b/],
    keywords: ["joker free", "bonus", "double", "pay"],
    answer: pageAnswer("jokers.joker-free"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    page_ref: ["jokers.joker-free"],
    related: ["pay-discard-win", "self-drawn-win", "extra-payments"],
  },
  {
    id: "joker-call-complete",
    category: "jokers",
    level: "core",
    question: "Can I call a discard and use a joker to complete the set?",
    patterns: [/\bcall\b.{0,40}\bjoker\b.{0,30}\b(complete|finish|fill)/, /\bjoker\b.{0,30}\b(complete|finish|fill).{0,20}\b(call|expose|set|group)/, /\bcall\b.{0,20}\b(with|using) (a |two |2 )?joker/, /\bjoker\b.{0,20}(from|in) (my|your) hand.{0,20}call/],
    keywords: ["call", "joker", "complete", "expose"],
    answer: pageAnswer("jokers.call-with-joker"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    page_ref: ["jokers.call-with-joker"],
    related: ["calling-discard", "joker-exchange", "expose-immediately"],
  },
  {
    id: "wall-game-jokers",
    category: "scoring",
    level: "advanced",
    question: "What happens to jokers at the end of a wall game?",
    patterns: [/\bjoker\b.{0,30}\bwall game\b/, /\bwall game\b.{0,30}\bjoker\b/],
    keywords: ["joker", "wall game"],
    answer: pageAnswer("jokers.wall-game"),
    varies_by_house: true,
    house_note: "Wall game payments are a house rule; agree on them before you play.",
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["jokers.wall-game"],
    source_url: `${RULES}/jokers`,
    related: ["wall-game", "wall-game-payment", "joker-free"],
  },
  {
    id: "charleston-passes",
    category: "charleston",
    level: "foundational",
    question: "How many passes are in the Charleston?",
    patterns: [/how many pass/, /\b(first|second) charleston\b/, /\b(right|across|left) pass\b/, /\border\b.{0,20}\bpass\b/, /\bpass\b.{0,20}\border\b/],
    keywords: ["charleston", "pass", "first", "second", "right", "across", "left"],
    answer: pageAnswer("charleston.passes"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["charleston.passes"],
    source_url: `${RULES}/charleston`,
    related: ["charleston", "courtesy-pass", "charleston-blind-pass"],
  },
  {
    id: "courtesy-pass",
    category: "charleston",
    level: "core",
    question: "What is a courtesy pass?",
    patterns: [/courtesy pass/, /\bcourtesy\b.{0,20}\b(optional|tile|across)/, /\bpass\b.{0,20}\b(across|opposite)\b.{0,20}\b(after|end|optional)/],
    keywords: ["courtesy", "pass", "optional", "across"],
    answer: pageAnswer("charleston.courtesy-pass"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    page_ref: ["charleston.courtesy-pass"],
    related: ["charleston-passes", "charleston", "look-before-pass"],
  },
  {
    id: "look-before-pass",
    category: "charleston",
    level: "core",
    question: "Can I look at tiles before passing them?",
    patterns: [/look.{0,20}(before|at).{0,20}pass/, /see.{0,20}tile.{0,20}pass/, /(allowed|can|may) (i|you|we) look/],
    keywords: ["look", "pass", "blind"],
    answer: pageAnswer("charleston.look"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    page_ref: ["charleston.look"],
    related: ["charleston-blind-pass", "charleston-passes", "courtesy-pass"],
  },
  {
    id: "wrong-pass-count",
    category: "charleston",
    level: "advanced",
    question: "What happens if someone passes the wrong number of tiles?",
    patterns: [/(fewer|less|wrong number|too many|too few|only (one|two|1|2)).{0,20}tile.{0,30}pass/, /pass.{0,20}(fewer|less|wrong number|too many|too few|only (one|two|1|2))/, /wrong.{0,10}pass/],
    keywords: ["pass", "wrong", "fewer", "count"],
    answer: pageAnswer("charleston.wrong-count"),
    varies_by_house: true,
    house_note: "Once play has started, tables handle a bad pass differently; agree on it before you begin.",
    confidence: "medium",
    source: "lvm_rules_page",
    page_ref: ["charleston.wrong-count"],
    source_url: `${RULES}/charleston`,
    related: ["charleston-passes", "dead-hand-triggers", "disputes"],
  },
  {
    id: "pung-vs-kong",
    category: "basics",
    level: "foundational",
    question: "What is the difference between a pung and a kong?",
    patterns: [/what (is|are) (a |an )?(pung|kong|quint|sextet)/, /(pung|kong|quint|sextet).{0,15}(vs|versus|or|and|difference).{0,15}(pung|kong|quint|sextet)/, /difference between.{0,10}(pung|kong)/, /how many tile.{0,20}(pung|kong|quint|sextet)/],
    keywords: ["pung", "kong", "quint", "sextet", "difference"],
    answer: pageAnswer("calling-tiles.pung-vs-kong"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    page_ref: ["calling-tiles.pung-vs-kong"],
    related: ["card-numbers", "jokers-basics", "calling-discard"],
  },
  {
    id: "most-recent-discard",
    category: "calling",
    level: "core",
    question: "Can I call any discard or only the most recent one?",
    patterns: [/(any|earlier|older|previous|last few|two ago).{0,20}discard/, /discard.{0,30}(earlier|ago|before|previous)/, /most recent/],
    keywords: ["discard", "recent", "earlier", "any"],
    answer: pageAnswer("calling-tiles.most-recent"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["calling-tiles.most-recent"],
    source_url: `${RULES}/calling-tiles`,
    related: ["calling-discard", "call-window", "out-of-turn"],
  },
  {
    id: "same-tile-two-calls",
    category: "calling",
    level: "advanced",
    question: "What happens when two players call the same tile?",
    patterns: [/(two|2|both|multiple|several).{0,20}(player|people).{0,20}call/, /call.{0,20}(same|the) (tile|discard).{0,20}(same time|at once|together)/, /same (tile|discard)/, /who (get|gets|has|win|take|takes).{0,20}(tile|priority|discard)/, /priority/],
    keywords: ["two", "both", "same", "priority", "call"],
    answer: pageAnswer("calling-tiles.two-callers"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    page_ref: ["calling-tiles.two-callers"],
    related: ["call-for-mahjong", "calling-discard", "call-window"],
  },
  {
    id: "call-for-mahjong",
    category: "calling",
    level: "core",
    question: "Can I call a tile for mahjong when it is not my turn?",
    patterns: [/call.{0,30}mahjong.{0,30}(not my turn|out of turn|any time|anytime)/, /(not my turn|out of turn).{0,30}mahjong/, /\bcall\b.{0,12}\b(for|to (complete|make|declare|get)) (mahjong|the win|a win)\b/, /(win|mahjong).{0,20}(on|from|with) (a |the )?(call|discard)/, /\bcall\b.{0,20}\bmahjong\b.{0,20}\b(turn|discard|tile)\b/],
    keywords: ["call", "mahjong", "win", "turn"],
    answer: pageAnswer("calling-tiles.call-for-mahjong"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    page_ref: ["calling-tiles.call-for-mahjong"],
    related: ["same-tile-two-calls", "discard-win", "false-mahjong"],
  },
  {
    id: "out-of-turn",
    category: "calling",
    level: "advanced",
    question: "What is calling out of turn?",
    patterns: [/out of turn/, /call.{0,20}(before|too early|too soon)/, /wrong turn/],
    keywords: ["out of turn", "turn", "early"],
    answer: pageAnswer("calling-tiles.out-of-turn"),
    varies_by_house: false,
    confidence: "high",
    source: "derived",
    page_ref: ["calling-tiles.out-of-turn"],
    related: ["most-recent-discard", "call-window", "dead-hand-triggers"],
  },
  {
    id: "call-concealed",
    category: "calling",
    level: "core",
    question: "Can I call a tile for a concealed group?",
    patterns: [/call.{0,30}(concealed|hidden|unexposed|in my hand|without exposing)/, /(concealed|hidden|unexposed).{0,30}call/, /keep.{0,20}(call|tile).{0,20}(hidden|in my hand|rack)/, /(concealed|hidden|unexposed) (group|set|pung|kong|part|section)/, /call.{0,20}tile.{0,20}(concealed|hidden)/],
    keywords: ["call", "concealed", "hidden", "expose"],
    answer: pageAnswer("calling-tiles.concealed"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    page_ref: ["calling-tiles.concealed"],
    related: ["closed-hand-final-tile", "expose-immediately", "open-vs-closed"],
  },
  {
    id: "expose-immediately",
    category: "calling",
    level: "core",
    question: "Do I have to expose tiles right away when I call?",
    patterns: [/expose.{0,30}(immediately|right away|when i call|at once)/, /(immediately|right away).{0,20}expose/, /(after|when) (i|you) call.{0,30}(expose|show|put down|lay down)/, /(show|put down|lay down|put).{0,20}(tile|set|group).{0,30}call/, /change.{0,20}expose/, /expose.{0,20}(change|fix|adjust)/],
    keywords: ["expose", "call", "immediately", "show", "change"],
    answer: pageAnswer("calling-tiles.expose"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    page_ref: ["calling-tiles.expose"],
    related: ["wrong-exposure", "call-concealed", "joker-call-complete"],
  },
  {
    id: "dead-hand-triggers",
    category: "dead-hands",
    level: "advanced",
    question: "What makes a hand dead?",
    patterns: [/what (makes|make|causes|cause).{0,20}dead/, /(when|why) (is|does|would).{0,20}(hand|i|someone).{0,20}dead/, /dead.{0,20}(trigger|reason|cause)/],
    keywords: ["dead", "make", "cause", "illegal", "why"],
    answer: pageAnswer("dead-hands.triggers"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    page_ref: ["dead-hands.triggers"],
    related: ["wrong-exposure", "called-dead", "dead-hand-pays"],
  },
  {
    id: "dead-hand-pays",
    category: "dead-hands",
    level: "advanced",
    question: "Does a dead hand still pay the winner?",
    patterns: [/dead.{0,40}\bpay\b/, /\bpay\b.{0,40}dead/, /dead.{0,30}(owe|money|still)/],
    keywords: ["dead", "pay", "winner"],
    answer: pageAnswer("dead-hands.pays"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["dead-hands.pays"],
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-draws", "called-dead", "pay-discard-win"],
  },
  {
    id: "dead-hand-draws",
    category: "dead-hands",
    level: "advanced",
    question: "Does a dead player keep drawing tiles?",
    patterns: [/dead.{0,40}(draw|discard|keep playing|continue|still play)/, /(draw|discard|keep playing|continue|still play).{0,40}dead/],
    keywords: ["dead", "draw", "continue", "sit out"],
    answer: pageAnswer("dead-hands.draws"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["dead-hands.draws"],
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-pays", "two-dead-hands", "called-dead"],
  },
  {
    id: "two-dead-hands",
    category: "dead-hands",
    level: "advanced",
    question: "What happens if two players have dead hands?",
    patterns: [/(two|2|both|multiple).{0,20}(player|people|hand).{0,20}dead/, /dead.{0,30}(two|2|both|multiple)/],
    keywords: ["two", "both", "dead"],
    answer: pageAnswer("dead-hands.two-dead"),
    varies_by_house: false,
    confidence: "high",
    source: "derived",
    page_ref: ["dead-hands.two-dead"],
    related: ["dead-hand-draws", "dead-hand-pays", "wall-game"],
  },
  {
    id: "card-numbers",
    category: "card",
    level: "foundational",
    question: "What do the numbers on the card mean?",
    patterns: [/(number|digit).{0,30}(on|in).{0,10}card/, /card.{0,20}(number|digit).{0,20}mean/, /what (does|do) (the )?(2|3|4|5|6) mean/, /read(ing)? the card/, /how (do|to) (i )?read/],
    keywords: ["number", "card", "mean", "read"],
    answer: pageAnswer("the-card.numbers"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/the-card`,
    page_ref: ["the-card.numbers"],
    related: ["any-like-number", "consecutive-numbers", "pung-vs-kong"],
  },
  {
    id: "any-like-number",
    category: "card",
    level: "core",
    question: "What does 'any like number' mean?",
    patterns: [/like number/, /any number/, /same number.{0,20}(suit|across)/],
    keywords: ["like", "number", "any"],
    answer: pageAnswer("the-card.like-number"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["the-card.like-number"],
    source_url: `${RULES}/the-card`,
    related: ["consecutive-numbers", "card-numbers", "open-vs-closed"],
  },
  {
    id: "consecutive-numbers",
    category: "card",
    level: "core",
    question: "What does 'consecutive numbers' mean?",
    patterns: [/consecutive/, /(run|sequence|in order|in a row).{0,20}(number|tile)/, /(number|tile).{0,20}(run|sequence|in order|in a row)/],
    keywords: ["consecutive", "run", "sequence"],
    answer: pageAnswer("the-card.consecutive"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["the-card.consecutive"],
    source_url: `${RULES}/the-card`,
    related: ["any-like-number", "card-numbers", "winning-mahjong"],
  },
  {
    id: "last-years-card",
    category: "card",
    level: "core",
    question: "Can I play with last year's card?",
    patterns: [/last year('s)? card/, /old(er)? card/, /(previous|prior|expired|out of date|outdated).{0,10}card/, /card.{0,20}(from|of) (last|previous|another) year/, /still (use|play).{0,20}card/],
    keywords: ["last year", "old", "card", "previous"],
    answer: pageAnswer("the-card.last-year"),
    varies_by_house: true,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["the-card.last-year"],
    source_url: `${RULES}/the-card`,
    related: ["annual-card", "card-numbers", "house-vs-nmjl"],
  },
  {
    id: "valid-mahjong",
    category: "winning",
    level: "core",
    question: "What makes a valid mahjong?",
    patterns: [/valid (mahjong|hand|win)/, /(mahjong|hand|win).{0,20}(valid|count|legal)/, /(exactly|must) match.{0,20}card/],
    keywords: ["valid", "mahjong", "match", "card"],
    answer: pageAnswer("winning.valid"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["winning.valid"],
    source_url: `${RULES}/winning`,
    related: ["false-mahjong", "winning-mahjong", "change-mind-mahjong"],
  },
  {
    id: "discard-win",
    category: "winning",
    level: "core",
    question: "Can I win on a tile someone else discards?",
    patterns: [/win.{0,30}(discard|call|someone else|another player)/, /(discard|call).{0,30}win/, /discard win/],
    keywords: ["win", "discard", "call"],
    answer: pageAnswer("winning.discard-win"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["winning.discard-win"],
    source_url: `${RULES}/winning`,
    related: ["self-drawn-win", "pay-discard-win", "call-for-mahjong"],
  },
  {
    id: "self-drawn-win",
    category: "winning",
    level: "core",
    question: "Can I win on my own draw?",
    patterns: [/self draw/, /(own|my) draw/, /draw.{0,20}(win|last|final) tile/, /win.{0,20}(from|off) the wall/, /\bpay\b.{0,30}self draw/, /self draw.{0,30}\bpay\b/],
    keywords: ["self", "draw", "own", "win", "pay"],
    answer:
      "A self-drawn win is drawing the tile you need from the wall to complete your hand; you declare mahjong the same way as on a called tile. Whether a self-drawn win pays more than a win on a discard is settled by your group; confirm your table's payment rules before play.",
    varies_by_house: true,
    confidence: "medium",
    source: "derived",
    page_ref: ["winning.self-drawn"],
    related: ["discard-win", "pay-discard-win", "joker-free"],
  },
  {
    id: "wall-game-payment",
    category: "scoring",
    level: "advanced",
    question: "How does payment work in a wall game?",
    patterns: [/wall game.{0,30}(pay|money|score|owe)/, /(pay|money|score|owe).{0,30}wall game/, /(nobody|no one) win.{0,30}(pay|money)/],
    keywords: ["wall game", "pay", "money"],
    answer: pageAnswer("scoring.wall-game"),
    varies_by_house: true,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["scoring.wall-game"],
    source_url: `${RULES}/scoring`,
    related: ["wall-game", "game-value", "wall-game-jokers"],
  },
  {
    id: "false-mahjong",
    category: "winning",
    level: "advanced",
    question: "What is a false mahjong?",
    patterns: [/false mahjong/, /(wrong|incorrect|bad|mistaken|accident).{0,20}mahjong/, /(call|declare).{0,10}mahjong.{0,30}(wrong|mistake|not valid|invalid|by mistake|error)/, /mahjong.{0,20}(by mistake|wrong|in error)/],
    keywords: ["false", "mahjong", "wrong", "penalty", "error"],
    answer: pageAnswer("winning.false-mahjong"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    page_ref: ["winning.false-mahjong"],
    related: ["change-mind-mahjong", "valid-mahjong", "dead-hand-triggers"],
  },
  {
    id: "change-mind-mahjong",
    category: "winning",
    level: "advanced",
    question: "Can I take back a mahjong call?",
    patterns: [/(take back|undo|retract|change (my|your) mind).{0,30}mahjong/, /mahjong.{0,30}(take back|undo|retract|change (my|your) mind)/],
    keywords: ["take back", "mahjong", "change", "mind"],
    answer: pageAnswer("winning.change-mind"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    page_ref: ["winning.change-mind"],
    related: ["false-mahjong", "valid-mahjong", "take-back-discard"],
  },
  {
    id: "passed-winning-tile",
    category: "winning",
    level: "core",
    question: "What if I passed my winning tile in the Charleston?",
    patterns: [/pass.{0,30}(win|needed|need|good|mahjong) tile/, /(win|needed) tile.{0,30}pass/, /gave away.{0,20}tile/, /pass.{0,20}(a|the|my) tile.{0,20}(need|want)/, /(win|need|needed|mahjong) tile.{0,30}(charleston|pass)/],
    keywords: ["pass", "winning", "tile", "charleston"],
    answer: pageAnswer("winning.passed-winning-tile"),
    varies_by_house: false,
    confidence: "high",
    source: "derived",
    page_ref: ["winning.passed-winning-tile"],
    related: ["charleston", "look-before-pass", "charleston-passes"],
  },
  {
    id: "pay-discard-win",
    category: "scoring",
    level: "advanced",
    question: "Who pays when someone wins on a discard?",
    patterns: [/who pay/, /\bpay\b.{0,30}(discard|call|thrower|threw|discarder)/, /(discard|discarder|thrower).{0,30}\bpay\b/, /pay double/, /how (much|does).{0,20}(discarder|thrower).{0,20}pay/],
    keywords: ["pay", "discard", "double", "who"],
    answer: pageAnswer("scoring.discard-pays"),
    varies_by_house: true,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["scoring.discard-pays"],
    source_url: `${RULES}/scoring`,
    related: ["self-drawn-win", "joker-free", "game-value"],
  },
  {
    id: "game-value",
    category: "scoring",
    level: "advanced",
    question: "How much is a hand worth?",
    patterns: [/how much.{0,20}(worth|bet|per hand|money|pay)/, /(game|hand) value/, /(cents|dollar|quarter).{0,30}(hand|game|point)/, /how (do|does).{0,20}(scoring|score|point).{0,20}work/],
    generic: [/(bet|stake|wager)/, /\bscor(e|ing)\b/],
    keywords: ["worth", "value", "bet", "score", "point"],
    answer: pageAnswer("scoring.game-value"),
    varies_by_house: true,
    house_note: "The amount per hand is always a group agreement.",
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["scoring.game-value"],
    source_url: `${RULES}/scoring`,
    related: ["pay-discard-win", "joker-free", "extra-payments"],
  },
  {
    id: "extra-payments",
    category: "scoring",
    level: "advanced",
    question: "Do any hands pay extra beyond joker-free?",
    patterns: [/(extra|bonus|double|triple).{0,30}(hand|pay|quint|single)/, /(quint|single).{0,20}(hand).{0,20}(pay|worth|double)/, /pay (extra|more|double|triple)/, /(beyond|besides|other than|except|apart from).{0,20}joker free/, /(extra|bonus|more).{0,20}(beyond|besides)/],
    keywords: ["extra", "bonus", "double", "triple", "pay"],
    answer: pageAnswer("scoring.extra"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/scoring`,
    page_ref: ["scoring.extra"],
    related: ["joker-free", "game-value", "pay-discard-win"],
  },
  {
    id: "take-back-discard",
    category: "etiquette",
    level: "core",
    question: "Can I take back a discard?",
    patterns: [/(take back|undo|retract|change (my|your) mind|pick back up|oops).{0,30}discard/, /discard.{0,30}(take back|undo|retract|change (my|your) mind|by mistake|accident)/, /(accident|mistake).{0,20}discard/],
    keywords: ["take back", "discard", "mistake", "accident"],
    answer: pageAnswer("etiquette.take-back"),
    varies_by_house: false,
    confidence: "high",
    source: "derived",
    page_ref: ["etiquette.take-back"],
    related: ["most-recent-discard", "change-mind-mahjong", "call-window"],
  },
  {
    id: "table-talk",
    category: "etiquette",
    level: "core",
    question: "What counts as table talk?",
    patterns: [/table talk/, /(talk|say|announce|tell).{0,30}(hand|need|looking for)/, /(hint|signal|comment).{0,30}(hand|discard|tile)/],
    keywords: ["talk", "table", "announce", "hint"],
    answer: pageAnswer("etiquette.table-talk"),
    varies_by_house: true,
    house_note: "Casual groups set their own table talk rules; competitive play prohibits it.",
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["etiquette.table-talk"],
    source_url: `${RULES}/etiquette`,
    related: ["courtesies-vs-rules", "see-exposed-tiles", "disputes"],
  },
  {
    id: "call-window",
    category: "calling",
    level: "core",
    question: "How fast do I have to call a discard?",
    patterns: [/how (fast|quick|long|soon).{0,30}call/, /how (fast|quick|long|soon)/, /(window|time|too late|late).{0,30}call/, /call.{0,30}(too late|late|window|before the next|next player draw|next player pick)/, /(next player|already) (draw|drew|pick|racked|rack)/],
    keywords: ["fast", "late", "window", "call", "draw", "rack"],
    answer: pageAnswer("etiquette.call-window"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/etiquette`,
    page_ref: ["etiquette.call-window"],
    related: ["most-recent-discard", "calling-discard", "take-back-discard"],
  },
  {
    id: "disputes",
    category: "etiquette",
    level: "core",
    question: "Who resolves a rules dispute?",
    patterns: [/who (decide|is right|has the final)/, /can'?t agree/, /(settle|resolve).{0,20}(dispute|argument|disagreement|rule)/],
    generic: [/(dispute|argument|disagree|argue|fight|settle|resolve)/],
    keywords: ["dispute", "disagree", "resolve", "argue"],
    answer: pageAnswer("etiquette.disputes"),
    varies_by_house: true,
    house_note: "Each group decides how it settles disputes; agree on it before you play.",
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["etiquette.disputes"],
    source_url: `${RULES}/etiquette`,
    related: ["house-vs-nmjl", "courtesies-vs-rules", "wrong-exposure"],
  },
  {
    id: "see-exposed-tiles",
    category: "etiquette",
    level: "core",
    question: "Can I look at another player's exposed tiles?",
    patterns: [/(look|see|view|check).{0,30}(another|other|someone|opponent).{0,20}(expose|tile|rack)/, /(expose|tile).{0,20}(visible|public|private|hidden)/],
    keywords: ["look", "see", "exposed", "rack"],
    answer: pageAnswer("etiquette.see-exposed"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["etiquette.see-exposed"],
    source_url: `${RULES}/etiquette`,
    related: ["joker-exchange", "table-talk", "expose-immediately"],
  },
  {
    id: "house-vs-nmjl",
    category: "etiquette",
    level: "core",
    question: "What is the difference between a house rule and an NMJL rule?",
    patterns: [/house rule.{0,20}(vs|versus|and|or).{0,20}(nmjl|official|league)/, /(nmjl|official|league).{0,20}(vs|versus|and|or).{0,20}house/, /what is (a |an )?(house|nmjl|official) rule/, /is (this|that|it) (a |an )?(house|official|nmjl|real|standard) rule/],
    generic: [/\bnmjl\b/, /official/],
    keywords: ["house", "nmjl", "official", "league", "rule"],
    answer: pageAnswer("etiquette.house-vs-nmjl"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    page_ref: ["etiquette.house-vs-nmjl"],
    source_url: `${RULES}/etiquette`,
    related: ["courtesies-vs-rules", "disputes", "annual-card"],
  },

  // ── Stitched from approved sentences (one Find My Mahj sentence plus page sentences) ──
  {
    id: "called-dead",
    category: "dead-hands",
    level: "advanced",
    question: "What happens if someone calls me dead?",
    patterns: [/(call|called|declare|declared|say|says|said).{0,15}(me|my hand|i am|i'm|you|your hand).{0,10}dead/, /(someone|somebody|another player|they).{0,20}(call|declare).{0,20}dead/, /dead.{0,20}(challenge|accuse)/, /(challenge|accuse).{0,20}dead/],
    keywords: ["dead", "called", "challenge"],
    answer:
      "Calling another player's hand dead is a formal challenge, so be sure you are right before you make it. Once a hand is declared dead, that player does not draw or discard for the rest of the hand. They sit out until the next hand begins. A player whose hand is declared dead must still pay the winner if someone else wins.",
    varies_by_house: true,
    house_note: "Tables enforce dead hand challenges with different levels of strictness.",
    confidence: "medium",
    source: "lvm_rules_page",
    page_ref: ["dead-hands.draws", "dead-hands.pays"],
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-triggers", "wrong-exposure", "disputes"],
  },
  {
    id: "wrong-exposure",
    category: "dead-hands",
    level: "advanced",
    question: "What happens if I expose the wrong tiles?",
    patterns: [/expose.{0,30}(wrong|incorrect|bad|mistake|by accident|accident)/, /(wrong|incorrect|bad|mistake).{0,30}expose/, /(wrong|incorrect).{0,20}(tile|set|group).{0,30}(table|down|out)/, /(put|lay|set) (down|out).{0,20}wrong/, /(save|saved|fix|correct|undo|take back).{0,30}(dead|mistake|error|exposure)/, /(mistake|error).{0,30}(before|catch|caught|notice)/, /(dead|mistake|error).{0,30}(save|fix|correct)/],
    keywords: ["expose", "wrong", "mistake", "incorrect", "save", "correct"],
    answer: pageAnswer("dead-hands.saved"),
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    page_ref: ["dead-hands.saved"],
    related: ["expose-immediately", "dead-hand-triggers", "called-dead"],
  },

  // ── Own-text entries: owner-approved on 2026-08-29, or pending instructor review ──
  {
    id: "call-during-charleston",
    category: "charleston",
    level: "core",
    question: "Can I call a tile during the Charleston?",
    patterns: [/call.{0,40}(during|in|before).{0,10}charleston/, /\bcall\b.{0,50}\bcharleston\b/, /charleston.{0,40}call/, /call.{0,20}(pass|passed) tile/, /(pass|passed) tile.{0,20}call/],
    keywords: ["call", "charleston", "pass"],
    answer:
      "No. The Charleston is the tile passing that happens before play begins, and the first discard only happens after the Charleston, when East opens play. There are no discards during the Charleston, so there is nothing to call.",
    varies_by_house: false,
    confidence: "high",
    source: "owner_approved",
    related: ["charleston", "calling-discard", "dealing"],
  },
  {
    id: "joker-in-news",
    category: "jokers",
    level: "core",
    question: "Can I use a joker in NEWS?",
    patterns: [/\bjoker\b.{0,40}\bnews\b/, /\bnews\b.{0,40}\bjoker\b/, /\bjoker\b.{0,30}\b(north|east|west|south)\b/, /\bwind\b.{0,30}\bjoker\b/],
    keywords: ["joker", "news", "wind"],
    answer:
      "No. NEWS is made up of four different tiles (North, East, West, and South), so each one counts as a single tile, and a joker can never be used as a single. Jokers only work inside groups of 3 or more identical tiles: a Pung, Kong, Quint, or Sextet.",
    varies_by_house: false,
    confidence: "high",
    source: "owner_approved",
    related: ["joker-in-pair", "joker-single", "winds"],
  },
  {
    id: "discarded-joker",
    category: "jokers",
    level: "core",
    question: "Can I pick up a discarded joker?",
    patterns: [/(pick up|call|take|claim|grab).{0,30}(discard|thrown).{0,15}joker/, /joker.{0,20}(discard|thrown|on the table).{0,40}(pick|call|take|claim|grab)/, /discard.{0,15}joker/, /joker.{0,15}discard/],
    keywords: ["joker", "discard", "pick up", "call"],
    answer:
      "The card's joker rule says a discarded joker can never be called for mahjong. Whether a discarded joker can be claimed for an exposure is not printed on the card; common table practice treats a discarded joker as out of the hand entirely, so check with your table. Under that practice, the only way to take a joker from the table is a joker exchange from an exposed group on your own turn.",
    varies_by_house: true,
    confidence: "high",
    source: "derived",
    related: ["joker-exchange", "calling-discard", "take-back-discard"],
  },
  {
    id: "call-for-pair",
    category: "calling",
    level: "core",
    question: "Can I call a tile to make a pair?",
    patterns: [/call.{0,30}\bpair\b/, /\bpair\b.{0,30}call/, /call.{0,20}(a )?single/],
    keywords: ["call", "pair", "single"],
    answer:
      "No. You may only call a discard for an exposed group of 3 or more identical tiles (a Pung, Kong, Quint, or Sextet), or when that tile completes your mahjong. A pair by itself cannot be called; the exception is when the pair is the last thing your hand needs, because then the call is for mahjong.",
    varies_by_house: false,
    confidence: "high",
    source: "owner_approved",
    related: ["calling-discard", "call-for-mahjong", "joker-in-pair"],
  },
];

// Entries that point at a /rules Q&A but deliberately keep their own wording. Each needs a
// reason; the truth-layer test fails on any other divergence, and on a stale entry here.
export const ALIGNMENT_EXCEPTIONS: Record<string, string> = {
  "self-drawn-win":
    "Same facts as winning.self-drawn, but that page answer opens with 'Yes', which reads wrong for the payment question this entry also answers.",
  "called-dead":
    "Stitched from one Find My Mahj sentence and two page sentences; every sentence is traced by the test.",
};

// The owner's 2026-08-29 decision: these six stay pending until she rules on each.
export const PENDING_BY_OWNER_DECISION = ["discarded-joker", "out-of-turn", "take-back-discard", "passed-winning-tile", "two-dead-hands", "self-drawn-win"];

export const KNOWLEDGE_BY_ID: ReadonlyMap<string, KnowledgeEntry> = new Map(
  RULES_KNOWLEDGE.map((e) => [e.id, e])
);
