// Ask a Mahjong Rule: the only place rule text may come from. Retrieval picks an entry
// and the optional model may rephrase one, but nothing may add rule content that is not
// written here. Annual NMJL card hands are copyrighted and must never appear in this file;
// lib/ask/engine.ts refuses those questions before retrieval.
//
// Sources, in order of authority:
//   shared_approved  verbatim copy of an owner-approved entry from Find My Mahj
//                    (findmymahjgame/lib/rules/knowledge.ts). Same id, same text. A test
//                    compares the two files whenever the sister repo is checked out beside
//                    this one, so the two sites cannot drift apart silently.
//   lvm_rules_page   verbatim text from a lasvegasmahj.com/rules page (source_url).
//   derived          composed only from approved statements above, but the exact wording
//                    has not yet been reviewed by the instructor. The UI labels these
//                    "Pending instructor review" until the owner flips the source.

export const CURRENT_CARD_YEAR = 2026;

export type AskCategory =
  | "tiles"
  | "jokers"
  | "charleston"
  | "calling"
  | "winning"
  | "scoring"
  | "dead-hands"
  | "card"
  | "etiquette"
  | "basics";

export type AskSource = "shared_approved" | "lvm_rules_page" | "derived";

export type AskLevel = "foundational" | "core" | "advanced";

export type KnowledgeEntry = {
  id: string;
  category: AskCategory;
  level: AskLevel;
  question: string;
  patterns: RegExp[];
  generic?: RegExp[];
  keywords: string[];
  answer: string;
  varies_by_house: boolean;
  house_note?: string;
  confidence: "high" | "medium";
  source: AskSource;
  source_url?: string;
  related: string[];
};

const RULES = "https://www.lasvegasmahj.com/rules";

export const RULES_KNOWLEDGE: KnowledgeEntry[] = [
  // ── Shared, owner-approved (verbatim from Find My Mahj) ──────────────────────
  {
    id: "tile-count",
    category: "tiles",
    level: "foundational",
    question: "How many tiles are in an American Mahjong set?",
    patterns: [
      /how many tile/,
      /tile (are|come|in) (a|an|the) (american )?(mahjong )?set/,
      /\b152\b/,
      /tile count/,
      /what('s| is) in (a|an|the) (american )?(mahjong )?set/,
      /how many (joker|flower|dragon|wind)/,
    ],
    keywords: ["152", "set", "how many"],
    answer:
      "An American mahjong set has 152 tiles: the three suits (Bams, Craks, and Dots) numbered 1 through 9 with 4 copies of each tile, 16 winds, 12 dragons, 8 flowers, and 8 jokers.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["suits", "jokers-basics", "the-wall"],
  },
  {
    id: "suits",
    category: "tiles",
    level: "foundational",
    question: "What are the three suits?",
    patterns: [/what (are|'re) the (three |3 )?suit/, /(three|3) suit/, /suit (in|of) (american )?mahjong/, /how many suit/, /\b(bam|crak|dot)\b.{0,30}\bsuit/, /\bsuit\b.{0,30}\b(bam|crak|dot)\b/, /name the suit/, /which suit/],
    generic: [/\bsuit\b/],
    keywords: ["suit", "bam", "crak", "dot"],
    answer:
      "American mahjong uses three suits: Bams, Craks, and Dots. Each suit runs from 1 to 9, and the set holds 4 copies of every suit tile.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["dragons", "tile-count", "winds"],
  },
  {
    id: "dragons",
    category: "tiles",
    level: "foundational",
    question: "Which dragon goes with which suit?",
    patterns: [/which dragon (goes|matches|belongs)/, /\bdragon\b.{0,30}\b(suit|bam|crak|dot|match|belong|go with)/, /\b(suit|bam|crak|dot)\b.{0,30}\bdragon\b/, /(red|green|soap) dragon/],
    generic: [/\bdragon\b/, /\bsoap\b/],
    keywords: ["dragon", "soap", "red", "green", "white"],
    answer:
      "American mahjong has three dragons, and each one belongs to a suit: the Red dragon goes with Craks, the Green dragon goes with Bams, and the White dragon, called the Soap, goes with Dots. The set holds 4 of each dragon, 12 dragon tiles in all.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["suits", "flowers", "winds"],
  },
  {
    id: "flowers",
    category: "tiles",
    level: "foundational",
    question: "Are flowers interchangeable?",
    patterns: [/are flower (numbered|interchangeable|the same)/, /flower.{0,30}(interchangeable|numbered|same|any|different|match)/],
    generic: [/\bflower\b/],
    keywords: ["flower"],
    answer:
      "Flowers are all interchangeable, and they are not numbered. Any flower can stand in for any other flower; a flower is a flower is a flower. An American set has 8 of them.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["dragons", "jokers-basics", "tile-count"],
  },
  {
    id: "winds",
    category: "tiles",
    level: "foundational",
    question: "How do the winds work?",
    patterns: [/north.{0,10}east.{0,10}west.{0,10}south/, /how (do|does).{0,10}wind/, /wind.{0,20}(suit|work|belong)/],
    generic: [/\bwind\b/],
    keywords: ["wind", "north", "south", "east", "west"],
    answer:
      "An American set includes 4 winds: North, East, West, and South, with 4 copies of each for 16 wind tiles in total. Winds do not belong to any suit.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["joker-in-news", "dragons", "dealing"],
  },
  {
    id: "jokers-basics",
    category: "jokers",
    level: "foundational",
    question: "How do jokers work?",
    patterns: [/what (is|are) (a )?joker/, /how (do|does) (a )?joker work/, /joker (wild|rule)/, /\bwild tile/, /\bjoker\b.{0,30}\b(pung|kong|quint|sextet|group|set)\b/, /\b(pung|kong|quint|sextet|group|set)\b.{0,30}\bjoker\b/],
    keywords: ["joker", "wild", "kong", "pung", "quint", "sextet"],
    answer:
      "Jokers are wild tiles, and they are unique to American mahjong. A joker can stand in for any tile inside a group of 3 or more, meaning a Pung, Kong, Quint, or Sextet. An American set has 8 jokers.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["joker-in-pair", "joker-exchange", "joker-substitute"],
  },
  {
    id: "joker-in-pair",
    category: "jokers",
    level: "core",
    question: "Can I use a joker in a pair?",
    patterns: [/\bjoker\b.{0,60}\b(pair|single)\b/, /\b(pair|single)\b.{0,60}\bjoker\b/],
    keywords: ["joker", "pair", "single"],
    answer:
      "No. A joker can never be used in a pair or as a single tile. Jokers only work inside groups of 3 or more: a Pung, Kong, Quint, or Sextet. Hands built entirely from singles and pairs take no jokers at all.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/jokers`,
    related: ["joker-substitute", "joker-exchange", "joker-in-news"],
  },
  {
    id: "joker-exchange",
    category: "jokers",
    level: "core",
    question: "When can I exchange a joker?",
    patterns: [/\bexchange\b.{0,30}\bjoker\b/, /\bjoker\b.{0,30}\bexchange\b/, /take.{0,20}\bjoker\b.{0,30}(expose|rack)/, /\bjoker\b.{0,40}\b(another|other|someone|somebody)('s)? (player|expose|set)/],
    keywords: ["joker", "exchange", "expose"],
    answer:
      "Yes, joker exchange is allowed. When any player has an exposed group on the table that contains a joker, you may, on your own turn, hand over the real tile that joker stands for and take the joker into your hand. You can only redeem a joker from an exposure, never from tiles hidden in another player's hand.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "discarded-joker", "joker-free"],
  },
  {
    id: "dealing",
    category: "basics",
    level: "foundational",
    question: "How many tiles does each player start with?",
    patterns: [/how many tile.{0,40}(start|deal|dealt|hand)/, /\bstart with\b/, /who (start|deal|goes first|is east)/, /\b(13|14) tile/, /\bdealer\b/, /\beast\b.{0,20}\b(14|first|discard)/],
    keywords: ["deal", "dealer", "start", "east", "first"],
    answer:
      "Each player starts with 13 tiles, except East, the dealer, who starts with 14. After the Charleston, East opens play by discarding a tile.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/winning`,
    related: ["the-wall", "charleston", "players-count"],
  },
  {
    id: "charleston",
    category: "charleston",
    level: "foundational",
    question: "How does the Charleston work?",
    patterns: [/(how|what).{0,20}charleston.{0,10}(work|is|go|mean)/, /what is (the |a )?charleston/, /\bpass\b.{0,20}\btile\b/, /\bstop\b.{0,30}\bcharleston\b/, /\bcharleston\b.{0,30}\b(stop|skip|refuse|optional|second|required|mandatory)\b/, /\bjoker\b.{0,30}\bpass\b/, /\bpass\b.{0,30}\bjoker\b/],
    generic: [/\bcharleston\b/],
    keywords: ["charleston", "pass", "blind", "second", "stop"],
    answer:
      "The Charleston is the tile passing that happens before play begins. In the first Charleston, every player passes 3 tiles right, then 3 across, then 3 left; this first round is required. If all four players agree, a second Charleston follows: 3 left, 3 across, 3 right. On the last pass of each Charleston you may pass blind, taking tiles from the pass coming to you without looking at them. Afterward, you and the player across from you may make an optional courtesy pass of up to 3 tiles. You may never pass a joker in the Charleston.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/charleston`,
    related: ["charleston-passes", "charleston-blind-pass", "call-during-charleston"],
  },
  {
    id: "charleston-blind-pass",
    category: "charleston",
    level: "core",
    question: "What is a blind pass?",
    patterns: [/blind pass/, /\bblind\b.{0,20}\bpass\b/, /\bpass\b.{0,20}\bblind\b/, /pass.{0,30}without look/],
    keywords: ["blind", "pass", "charleston"],
    answer:
      "A blind pass is allowed only on the last pass of each Charleston: First Left and, if a second Charleston is played, Last Right. If you do not want to pass three tiles from your own hand, you may take one, two, or all three tiles being passed to you and pass them onward without looking at them. You still pass three tiles total.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/charleston`,
    related: ["charleston-passes", "look-before-pass", "courtesy-pass"],
  },
  {
    id: "open-vs-closed",
    category: "card",
    level: "core",
    question: "What is the difference between an open and a closed hand?",
    patterns: [/\b(open|closed|concealed)\b.{0,20}\bhand\b/, /\bhand\b.{0,20}\b(open|closed|concealed)\b/, /what does concealed mean/, /difference between open and closed/],
    keywords: ["open", "closed", "concealed", "hand"],
    answer:
      "Open hands can call discards to build exposed groups. Closed hands, also called concealed hands, must be built from your own draws, with no calling to build groups; the only discard a closed hand may claim is the single tile that completes your mahjong.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/the-card`,
    related: ["closed-hand-final-tile", "calling-discard", "call-concealed"],
  },
  {
    id: "closed-hand-final-tile",
    category: "card",
    level: "advanced",
    question: "Can a closed hand call its final tile?",
    patterns: [/\b(closed|concealed)\b.{0,30}\b(call|pick up|take)\b/, /\b(call|pick up|take)\b.{0,30}\b(closed|concealed)\b/, /\b(closed|concealed)\b.{0,45}\b(discard|mahjong)\b/, /\b(closed|concealed)\b.{0,40}\b(final|last|win) tile\b/, /\b(final|last) tile\b.{0,40}\b(mahjong|win|closed|concealed)\b/],
    keywords: ["closed", "concealed", "final", "last", "call"],
    answer:
      "A closed (concealed) hand may not call any discard to build a group. The one exception: you may claim a discard when it is the single tile that completes your mahjong.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/the-card`,
    related: ["open-vs-closed", "call-for-mahjong", "calling-discard"],
  },
  {
    id: "calling-discard",
    category: "calling",
    level: "core",
    question: "When can I call a discard?",
    patterns: [/\bcall\b.{0,20}\b(discard|tile)\b/, /when can (i|you) call/, /(pick up|take(?! back)).{0,20}\b(discard|thrown tile)\b/, /how (do|does) call/],
    generic: [/\bdiscard\b/, /\bcall\b/],
    keywords: ["call", "discard"],
    answer:
      "You may call the most recent discard when you can use it right away in an exposed group of 3 or more identical tiles, with jokers allowed to fill in, or when it completes your mahjong. When you call for a group, you must place that group face up on your rack. A call for mahjong beats a call for an exposure.",
    varies_by_house: true,
    house_note:
      "Tables differ on exactly when the calling window closes after the next player draws, so agree on it before you start.",
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/calling-tiles`,
    related: ["same-tile-two-calls", "call-for-pair", "call-window"],
  },
  {
    id: "winning-mahjong",
    category: "winning",
    level: "foundational",
    question: "How do you win a hand?",
    patterns: [/how (do|does) (i|you|someone|a player) win/, /what (is|does) mahjong( mean)?/, /declar(e|ing) mahjong/, /\bwin hand\b/, /what counts as (a win|mahjong)/, /how (many|much) tile.{0,20}(win|mahjong)/],
    keywords: ["win", "declare", "mahjong", "14"],
    answer:
      "You win by completing a 14 tile hand that exactly matches one of the hands printed on the current National Mah Jongg League card, then declaring mahjong. The 14th tile can come from your own draw or from a called discard.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/winning`,
    related: ["valid-mahjong", "false-mahjong", "self-drawn-win"],
  },
  {
    id: "annual-card",
    category: "card",
    level: "foundational",
    question: "When does the new card come out?",
    patterns: [/(new|annual|yearly|current|next).{0,15}\bcard\b/, /\bcard\b.{0,25}(come(s)? out|release|publish)/, /when.{0,30}\bcard\b/, /what is the (nmjl |league )?card/, /\bcard\b.{0,20}\b(change|every year|each year)/],
    keywords: ["card", "nmjl", "league", "year"],
    answer:
      "The National Mah Jongg League publishes a new official card every spring. The card lists the hands you can win with, and those hands change every year, so players buy the new card each season directly from the League.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/the-card`,
    related: ["last-years-card", "card-numbers", "winning-mahjong"],
  },
  {
    id: "the-wall",
    category: "basics",
    level: "foundational",
    question: "How is the wall built?",
    patterns: [/build(ing)? the wall/, /how (is|are) the (tile|wall) (set|built|arranged)/, /how (long|tall|big|many).{0,20}wall(?! game)/, /what is (the |a )?wall(?! game)/],
    generic: [/\bwall\b(?! game)/],
    keywords: ["wall", "build"],
    answer:
      "After all 152 tiles are shuffled face down, each player builds a wall 19 tiles long and 2 tiles high. The four walls together hold the whole set, and every deal and draw comes from the wall.",
    varies_by_house: false,
    confidence: "high",
    source: "shared_approved",
    related: ["dealing", "wall-game", "tile-count"],
  },
  {
    id: "wall-game",
    category: "winning",
    level: "core",
    question: "What is a wall game?",
    patterns: [/wall game/, /(nobody|no one) (win|declared)/, /run(s|ning)? out of tile/, /end(s)? in a (draw|tie)/],
    keywords: ["wall game", "draw", "no winner", "nobody"],
    answer:
      "If the wall runs out of tiles before anyone declares mahjong, the hand ends with no winner. This is called a wall game, and no one scores it.",
    varies_by_house: true,
    house_note: "Tables differ on whether the same dealer deals again after a wall game.",
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/winning`,
    related: ["wall-game-payment", "the-wall", "winning-mahjong"],
  },
  {
    id: "players-count",
    category: "basics",
    level: "foundational",
    question: "How many players do you need?",
    patterns: [/how many (player|people)/, /play with (three|3|five|5|two|2)/, /number of player/, /\b(three|3) (player|people)\b/],
    keywords: ["player", "how many", "four", "three"],
    answer:
      "American mahjong is built for 4 players. Many groups adapt it when only 3 can play, but the standard game seats 4.",
    varies_by_house: true,
    house_note: "Adaptations for 3 players vary from table to table; agree on the format before you start.",
    confidence: "high",
    source: "shared_approved",
    related: ["dealing", "the-wall", "tile-count"],
  },
  {
    id: "courtesies-vs-rules",
    category: "etiquette",
    level: "core",
    question: "What is the difference between a rule and a house rule?",
    patterns: [/(table|house) rule/, /\bcourtes(y|ies)\b(?! pass)/, /\betiquette\b/, /rule (vs|versus|or) (courtes|custom)/, /official rule/],
    keywords: ["etiquette", "courtesy", "house", "official"],
    answer:
      "It helps to separate official rules from table courtesies. Official rules come from the National Mah Jongg League and apply everywhere, such as the tile count and how calling works. Courtesies are local customs a table agrees on, such as whether to make the courtesy pass in the Charleston or how strictly discards are announced. Agree on courtesies before the first hand so no one is surprised.",
    varies_by_house: true,
    house_note: "Courtesies differ from table to table by design.",
    confidence: "high",
    source: "shared_approved",
    source_url: `${RULES}/etiquette`,
    related: ["house-vs-nmjl", "table-talk", "disputes"],
  },
  {
    id: "dead-hand",
    category: "dead-hands",
    level: "advanced",
    question: "What is a dead hand?",
    patterns: [/what is (a )?dead hand/, /declar(e|ed|ing) (a hand |someone )?dead/, /dead hand.{0,10}(mean|rule)/],
    generic: [/dead hand/, /hand (is |goes )?dead/, /\bdead\b/],
    keywords: ["dead"],
    answer:
      "A hand is dead when it can no longer win, for example when a player holds the wrong number of tiles or has exposures that cannot fit any hand on the card. A dead player stops drawing and discarding for the rest of that hand. Calling another player's hand dead is a formal challenge, so be sure you are right before you make it.",
    varies_by_house: true,
    house_note: "Tables enforce dead hand challenges with different levels of strictness.",
    confidence: "medium",
    source: "shared_approved",
    source_url: `${RULES}/dead-hands`,
    related: ["called-dead", "dead-hand-triggers", "dead-hand-pays"],
  },

  // ── Las Vegas Mahjong rules pages (verbatim) ─────────────────────────────────
  {
    id: "joker-substitute",
    category: "jokers",
    level: "core",
    question: "What tiles can jokers substitute for?",
    patterns: [/\bjoker\b.{0,30}\b(substitute|stand in|replace|use[sd]? (for|as|in))/, /what can (a )?joker/, /\bjoker\b.{0,20}\b(kong|pung|quint)\b/, /\b(kong|pung|quint)\b.{0,20}\bjoker\b/],
    keywords: ["joker", "substitute", "kong", "pung", "quint"],
    answer:
      "Jokers can substitute for any tile in a set of three or more identical tiles: a pung (3), kong (4), or quint (5). They cannot substitute in pairs or single tiles. So jokers work in groups, never alone or in twos.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-exchange", "joker-call-complete"],
  },
  {
    id: "joker-single",
    category: "jokers",
    level: "core",
    question: "Can a joker be used as a single tile?",
    patterns: [/\bjoker\b.{0,30}\bsingle\b/, /\bsingle\b.{0,30}\bjoker\b/],
    keywords: ["joker", "single", "slot"],
    answer:
      "No. A single tile position on the card requires a real tile. Jokers only work in groups of three or more.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-in-news", "joker-substitute"],
  },
  {
    id: "joker-singles-pairs-hand",
    category: "jokers",
    level: "core",
    question: "Can I use a joker in a Singles and Pairs hand?",
    patterns: [/single.{0,5}(and|&).{0,5}pair/, /singles? pair/],
    keywords: ["single", "pair", "joker"],
    answer:
      "No. Singles and Pairs hands (hands with all single tiles and pairs) are joker-free by definition. No jokers anywhere in those hands.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-free", "joker-single"],
  },
  {
    id: "joker-free",
    category: "scoring",
    level: "advanced",
    question: "What is a joker-free hand and what does it pay?",
    patterns: [/joker free/, /\b(no|zero|without) joker/, /\bjoker\b.{0,20}\b(bonus|double|extra)\b/],
    keywords: ["joker free", "bonus", "double", "pay"],
    answer:
      "A joker-free hand is any complete mahjong hand that contains zero jokers. These hands pay double from all three players, meaning you collect twice the normal amount. This applies to self-drawn wins too.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    related: ["pay-discard-win", "pay-self-drawn", "extra-payments"],
  },
  {
    id: "joker-call-complete",
    category: "jokers",
    level: "core",
    question: "Can I call a discard and use a joker to complete the set?",
    patterns: [/\bcall\b.{0,40}\bjoker\b.{0,30}\b(complete|finish|fill)/, /\bjoker\b.{0,30}\b(complete|finish|fill).{0,20}\b(call|expose|set|group)/, /\bcall\b.{0,20}\b(with|using) (a )?joker/],
    keywords: ["call", "joker", "complete", "expose"],
    answer:
      "Yes. When you call a discard to complete a pung, kong, or quint, you can use jokers to fill the remaining tiles in that exposed group. You just need the called tile plus at least one real matching tile in the group.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    related: ["calling-discard", "joker-exchange", "expose-immediately"],
  },
  {
    id: "wall-game-jokers",
    category: "scoring",
    level: "advanced",
    question: "What happens to jokers at the end of a wall game?",
    patterns: [/\bjoker\b.{0,30}\bwall game\b/, /\bwall game\b.{0,30}\bjoker\b/],
    keywords: ["joker", "wall game"],
    answer:
      "In a wall game (nobody wins), there is no payment for jokers specifically. Each player pays the others based on house rules; most groups pay a flat amount per player per wall game.",
    varies_by_house: true,
    house_note: "Wall game payments are a house rule; agree on them before you play.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/jokers`,
    related: ["wall-game", "wall-game-payment", "joker-free"],
  },
  {
    id: "charleston-passes",
    category: "charleston",
    level: "foundational",
    question: "How many passes are in the Charleston?",
    patterns: [/how many pass/, /\b(first|second) charleston\b/, /\b(right|across|left) pass\b/, /\border\b.{0,20}\bpass\b/, /\bpass\b.{0,20}\border\b/],
    keywords: ["charleston", "pass", "first", "second", "right", "across", "left"],
    answer:
      "The first charleston has three mandatory passes: first right (3 tiles), first across (3 tiles), and first left (3 tiles). After the first charleston, players may agree to a second charleston with the same three passes in reverse order: second left, second across, second right. The second charleston requires all four players to agree.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    related: ["charleston", "courtesy-pass", "charleston-blind-pass"],
  },
  {
    id: "courtesy-pass",
    category: "charleston",
    level: "core",
    question: "What is a courtesy pass?",
    patterns: [/courtesy pass/, /\bcourtesy\b.{0,20}\b(optional|tile|across)/, /\bpass\b.{0,20}\b(across|opposite)\b.{0,20}\b(after|end|optional)/],
    keywords: ["courtesy", "pass", "optional", "across"],
    answer:
      "After both charlestons are complete, players may offer a courtesy pass (exchanging 1 to 3 tiles with the player across from you). Both players must agree on how many tiles to exchange, and both pass simultaneously. It is optional and either player can decline.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    related: ["charleston-passes", "charleston", "look-before-pass"],
  },
  {
    id: "look-before-pass",
    category: "charleston",
    level: "core",
    question: "Can I look at tiles before passing them?",
    patterns: [/look.{0,20}(before|at).{0,20}pass/, /see.{0,20}tile.{0,20}pass/, /(allowed|can|may) (i|you|we) look/],
    keywords: ["look", "pass", "blind"],
    answer:
      "Yes, except during a blind pass. In all other passes you see and choose which 3 tiles to pass. During a blind pass, you may pass tiles you just received without looking at them, but you are not required to; you can look and still pass them.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    related: ["charleston-blind-pass", "charleston-passes", "courtesy-pass"],
  },
  {
    id: "wrong-pass-count",
    category: "charleston",
    level: "advanced",
    question: "What happens if someone passes the wrong number of tiles?",
    patterns: [/(fewer|less|wrong number|too many|too few|only (one|two|1|2)).{0,20}tile.{0,30}pass/, /pass.{0,20}(fewer|less|wrong number|too many|too few|only (one|two|1|2))/, /wrong.{0,10}pass/],
    keywords: ["pass", "wrong", "fewer", "count"],
    answer:
      "If a player passes the wrong number of tiles and it is caught before play begins, the pass should be corrected. If it is caught after the first tile is drawn, house rules typically apply. The standard remedy is to correct the count if possible, or replay the charleston if necessary.",
    varies_by_house: true,
    house_note: "Once play has started, tables handle a bad pass differently; agree on it before you begin.",
    confidence: "medium",
    source: "lvm_rules_page",
    source_url: `${RULES}/charleston`,
    related: ["charleston-passes", "dead-hand-triggers", "disputes"],
  },
  {
    id: "pung-vs-kong",
    category: "basics",
    level: "foundational",
    question: "What is the difference between a pung and a kong?",
    patterns: [/what (is|are) (a |an )?(pung|kong|quint|sextet)/, /(pung|kong|quint|sextet).{0,15}(vs|versus|or|and|difference).{0,15}(pung|kong|quint|sextet)/, /difference between.{0,10}(pung|kong)/, /how many tile.{0,20}(pung|kong|quint|sextet)/],
    keywords: ["pung", "kong", "quint", "sextet", "difference"],
    answer:
      "A pung is a set of three identical tiles. A kong is a set of four. A quint is five, and a sextet is six (both require jokers). The card shows which group size each hand requires using the numbers 3, 4, 5, and 6.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    related: ["card-numbers", "jokers-basics", "calling-discard"],
  },
  {
    id: "most-recent-discard",
    category: "calling",
    level: "core",
    question: "Can I call any discard or only the most recent one?",
    patterns: [/(any|earlier|older|previous|last few|two ago).{0,20}discard/, /discard.{0,30}(earlier|ago|before|previous)/, /most recent/],
    keywords: ["discard", "recent", "earlier", "any"],
    answer:
      "You can only call the most recently discarded tile, the one that was just discarded by the player whose turn just ended. You cannot call a tile that was discarded earlier in the game.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    related: ["calling-discard", "call-window", "out-of-turn"],
  },
  {
    id: "same-tile-two-calls",
    category: "calling",
    level: "advanced",
    question: "What happens when two players call the same tile?",
    patterns: [/(two|2|both|multiple|several).{0,20}(player|people).{0,20}call/, /call.{0,20}(same|the) (tile|discard).{0,20}(same time|at once|together)/, /same (tile|discard)/, /who (get|has|wins|takes).{0,20}(tile|priority|discard)/, /priority/],
    keywords: ["two", "both", "same", "priority", "call"],
    answer:
      "The player calling for mahjong (to win) has priority over all other calls regardless of seating position. Among players calling for a pung, kong, or quint (not mahjong), the player who would receive the tile in the natural turn order takes priority (specifically, the player closest to the discarder going counterclockwise).",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    related: ["call-for-mahjong", "calling-discard", "call-window"],
  },
  {
    id: "call-for-mahjong",
    category: "calling",
    level: "core",
    question: "Can I call a tile for mahjong when it is not my turn?",
    patterns: [/call.{0,30}mahjong.{0,30}(not my turn|out of turn|any time|anytime)/, /(not my turn|out of turn).{0,30}mahjong/, /call.{0,20}(win|mahjong)/, /(win|mahjong).{0,20}(on|from|with) (a |the )?(call|discard)/],
    keywords: ["call", "mahjong", "win", "turn"],
    answer:
      "Yes. Any player can call any discard to complete a winning hand (mahjong). This overrides all other calls and any order of play.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    related: ["same-tile-two-calls", "discard-win", "false-mahjong"],
  },
  {
    id: "out-of-turn",
    category: "calling",
    level: "advanced",
    question: "What is calling out of turn?",
    patterns: [/out of turn/, /call.{0,20}(before|too early|too soon)/, /wrong turn/],
    keywords: ["out of turn", "turn", "early"],
    answer:
      "Calling a tile that is not the most recent discard, or calling before the discard is complete, is an out-of-turn call. The penalty varies by house rules but typically results in the hand being declared dead. At minimum, the call is void and play continues.",
    varies_by_house: true,
    house_note: "The penalty for an out-of-turn call is set by house rules.",
    confidence: "medium",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    related: ["most-recent-discard", "dead-hand-triggers", "call-window"],
  },
  {
    id: "call-concealed",
    category: "calling",
    level: "core",
    question: "Can I call a tile for a concealed group?",
    patterns: [/call.{0,30}(concealed|hidden|unexposed|in my hand|without exposing)/, /(concealed|hidden|unexposed).{0,30}call/, /keep.{0,20}(call|tile).{0,20}(hidden|in my hand|rack)/],
    keywords: ["call", "concealed", "hidden", "expose"],
    answer:
      "No. You can only call a discarded tile to complete a group that will be immediately exposed on the table. You cannot call a tile to add to a concealed section of your hand.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    related: ["closed-hand-final-tile", "expose-immediately", "open-vs-closed"],
  },
  {
    id: "expose-immediately",
    category: "calling",
    level: "core",
    question: "Do I have to expose tiles right away when I call?",
    patterns: [/expose.{0,30}(immediately|right away|when i call|at once)/, /(immediately|right away).{0,20}expose/, /(after|when) (i|you) call.{0,30}(expose|show|put down|lay down)/, /(show|put down|lay down|place).{0,20}(tile|set|group).{0,30}call/],
    keywords: ["expose", "call", "immediately", "show"],
    answer:
      "Yes. When you call a tile, you must immediately expose the full group (pung, kong, quint, or mahjong) to the table. You cannot call and then decide what to do; the declaration and exposure happen together.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/calling-tiles`,
    related: ["wrong-exposure", "call-concealed", "joker-call-complete"],
  },
  {
    id: "dead-hand-triggers",
    category: "dead-hands",
    level: "advanced",
    question: "What makes a hand dead?",
    patterns: [/what (makes|make|causes|cause).{0,20}dead/, /(when|why) (is|does|would).{0,20}(hand|i|someone).{0,20}dead/, /dead.{0,20}(trigger|reason|cause)/],
    keywords: ["dead", "make", "cause", "illegal", "why"],
    answer:
      "A hand is declared dead when a player makes an illegal or impossible call, exposes tiles incorrectly, calls an out-of-turn tile, or exposes a set that cannot possibly complete a valid hand on the current card. False mahjong also results in a dead hand. House rules vary slightly; your group should agree on the list of dead-hand triggers before play.",
    varies_by_house: true,
    house_note: "Groups differ on the exact list of dead-hand triggers; agree on it before play.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-saved", "called-dead", "dead-hand-pays"],
  },
  {
    id: "dead-hand-saved",
    category: "dead-hands",
    level: "advanced",
    question: "Can a hand be saved before it is declared dead?",
    patterns: [/(save|saved|fix|correct|undo|take back).{0,30}(dead|mistake|error|exposure)/, /(mistake|error).{0,30}(before|catch|caught|notice)/, /(dead|mistake|error).{0,30}(save|fix|correct)/],
    keywords: ["save", "correct", "mistake", "error", "dead"],
    answer:
      "Yes, in some situations. If a player notices an error before other players have acted on it (before the next player draws), the group may agree to correct it. Once play has advanced past the error, the hand is typically dead. The key is catching it immediately.",
    varies_by_house: true,
    house_note: "Whether a group allows a correction is a table decision.",
    confidence: "medium",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    related: ["wrong-exposure", "dead-hand-triggers", "disputes"],
  },
  {
    id: "dead-hand-pays",
    category: "dead-hands",
    level: "advanced",
    question: "Does a dead hand still pay the winner?",
    patterns: [/dead.{0,40}\bpay\b/, /\bpay\b.{0,40}dead/, /dead.{0,30}(owe|money|still)/],
    keywords: ["dead", "pay", "winner"],
    answer:
      "Yes. A player whose hand is declared dead must still pay the winner if someone else wins. Their hand being dead does not excuse them from payment obligations for the rest of that game.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-draws", "called-dead", "pay-discard-win"],
  },
  {
    id: "dead-hand-draws",
    category: "dead-hands",
    level: "advanced",
    question: "Does a dead player keep drawing tiles?",
    patterns: [/dead.{0,40}(draw|discard|keep playing|continue|still play)/, /(draw|discard|keep playing|continue|still play).{0,40}dead/],
    keywords: ["dead", "draw", "continue", "sit out"],
    answer:
      "No. Once a hand is declared dead, that player does not draw or discard for the rest of the hand. They sit out until the next hand begins.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-pays", "two-dead-hands", "called-dead"],
  },
  {
    id: "two-dead-hands",
    category: "dead-hands",
    level: "advanced",
    question: "What happens if two players have dead hands?",
    patterns: [/(two|2|both|multiple).{0,20}(player|people|hand).{0,20}dead/, /dead.{0,30}(two|2|both|multiple)/],
    keywords: ["two", "both", "dead"],
    answer:
      "Both sit out. The remaining two players continue, and both dead-hand players still pay if one of the active players wins.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-draws", "dead-hand-pays", "wall-game"],
  },
  {
    id: "card-numbers",
    category: "card",
    level: "foundational",
    question: "What do the numbers on the card mean?",
    patterns: [/(number|digit).{0,30}(on|in).{0,10}card/, /card.{0,20}(number|digit).{0,20}mean/, /what (does|do) (the )?(2|3|4|5|6) mean/, /read(ing)? the card/, /how (do|to) (i )?read/],
    keywords: ["number", "card", "mean", "read"],
    answer:
      "The numbers on the card tell you how many identical tiles are in that group: 2 is a Pair, 3 is a Pung, 4 is a Kong, 5 is a Quint, 6 is a Sextet. When you see a number placeholder like 'any like number,' that means you pick the number yourself and use it consistently throughout that hand.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/the-card`,
    related: ["any-like-number", "consecutive-numbers", "pung-vs-kong"],
  },
  {
    id: "any-like-number",
    category: "card",
    level: "core",
    question: "What does 'any like number' mean?",
    patterns: [/like number/, /any number/, /same number.{0,20}(suit|across)/],
    keywords: ["like", "number", "any"],
    answer:
      "'Any like number' means you can choose any number (1 through 9) and use that same number across the required suits. For example, if the hand calls for 3 Bams, 3 Craks, and 3 Dots of 'any like number,' all three sets must use the same number (say, all 4s).",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/the-card`,
    related: ["consecutive-numbers", "card-numbers", "open-vs-closed"],
  },
  {
    id: "consecutive-numbers",
    category: "card",
    level: "core",
    question: "What does 'consecutive numbers' mean?",
    patterns: [/consecutive/, /(run|sequence|in order|in a row).{0,20}(number|tile)/, /(number|tile).{0,20}(run|sequence|in order|in a row)/],
    keywords: ["consecutive", "run", "sequence"],
    answer:
      "Consecutive numbers are sequential: 1-2-3, or 4-5-6, etc. The hand will specify how many consecutive numbers you need and in which suits. You choose the starting number, but all tiles must follow in order without gaps.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/the-card`,
    related: ["any-like-number", "card-numbers", "winning-mahjong"],
  },
  {
    id: "last-years-card",
    category: "card",
    level: "core",
    question: "Can I play with last year's card?",
    patterns: [/last year('s)? card/, /old(er)? card/, /(previous|prior|expired|out of date|outdated).{0,10}card/, /card.{0,20}(from|of) (last|previous|another) year/, /still (use|play).{0,20}card/],
    keywords: ["last year", "old", "card", "previous"],
    answer:
      "Not in official or competitive play. The NMJL releases a new card each year and play should use the current year's card. However, in casual home games, groups sometimes agree to use any card they have; just make sure everyone is playing from the same card.",
    varies_by_house: true,
    house_note: "Casual groups sometimes agree to use an older card; official play always uses the current year's card.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/the-card`,
    related: ["annual-card", "card-numbers", "house-vs-nmjl"],
  },
  {
    id: "valid-mahjong",
    category: "winning",
    level: "core",
    question: "What makes a valid mahjong?",
    patterns: [/valid (mahjong|hand|win)/, /(mahjong|hand|win).{0,20}(valid|count|legal)/, /(exactly|must) match.{0,20}card/],
    keywords: ["valid", "mahjong", "match", "card"],
    answer:
      "A valid mahjong is a complete hand of 14 tiles that exactly matches one of the hands on the current year's NMJL card. Every tile must be in the right position, every suit must be correct, and exposed sets must match what you declared. If any element is off, it is not a valid mahjong.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    related: ["false-mahjong", "winning-mahjong", "change-mind-mahjong"],
  },
  {
    id: "discard-win",
    category: "winning",
    level: "core",
    question: "Can I win on a tile someone else discards?",
    patterns: [/win.{0,30}(discard|call|someone else|another player)/, /(discard|call).{0,30}win/, /discard win/],
    keywords: ["win", "discard", "call"],
    answer:
      "Yes. You can win by calling a discarded tile from any other player to complete your hand. This is called a 'discard win.' You declare mahjong, expose your full winning hand, and collect payment.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    related: ["self-drawn-win", "pay-discard-win", "call-for-mahjong"],
  },
  {
    id: "self-drawn-win",
    category: "winning",
    level: "core",
    question: "Can I win on my own draw?",
    patterns: [/self.?draw/, /(own|my) draw/, /draw.{0,20}(winning|last|final) tile/, /win.{0,20}(from|off) the wall/],
    keywords: ["self", "draw", "own", "win"],
    answer:
      "Yes. Drawing the tile you need from the wall to complete your hand is called a 'self-drawn win.' Self-drawn wins still pay the standard amount, though some groups play that self-drawn pays double; confirm your group's house rules.",
    varies_by_house: true,
    house_note: "Some groups pay double for a self-drawn win; confirm your table's rule.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    related: ["pay-self-drawn", "discard-win", "joker-free"],
  },
  {
    id: "wall-game-payment",
    category: "scoring",
    level: "advanced",
    question: "How does payment work in a wall game?",
    patterns: [/wall game.{0,30}(pay|money|score|owe)/, /(pay|money|score|owe).{0,30}wall game/, /(nobody|no one) win.{0,30}(pay|money)/],
    keywords: ["wall game", "pay", "money"],
    answer:
      "In a wall game (no winner), the NMJL standard is that no money changes hands. However, most groups play a house rule where each player pays every other player a small flat amount. Decide your group's wall game rule before play begins so there is no dispute.",
    varies_by_house: true,
    house_note: "Wall game payments are a common house rule; the NMJL standard is no payment.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/scoring`,
    related: ["wall-game", "game-value", "wall-game-jokers"],
  },
  {
    id: "false-mahjong",
    category: "winning",
    level: "advanced",
    question: "What is a false mahjong?",
    patterns: [/false mahjong/, /(wrong|incorrect|bad|mistaken|accident).{0,20}mahjong/, /(call|declare).{0,10}mahjong.{0,30}(wrong|mistake|not valid|invalid|by mistake)/, /mahjong.{0,20}(by mistake|wrong)/],
    keywords: ["false", "mahjong", "wrong", "penalty"],
    answer:
      "A false mahjong is calling mahjong when your hand does not actually complete a valid hand on the card. The penalty is set by house rules but typically means the player pays each other player the value of a full win. Play continues without that player; their hand is dead for the rest of the game.",
    varies_by_house: true,
    house_note: "The false mahjong penalty amount is set by house rules.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    related: ["change-mind-mahjong", "valid-mahjong", "dead-hand-triggers"],
  },
  {
    id: "change-mind-mahjong",
    category: "winning",
    level: "advanced",
    question: "Can I take back a mahjong call?",
    patterns: [/(take back|undo|retract|change (my|your) mind).{0,30}mahjong/, /mahjong.{0,30}(take back|undo|retract|change (my|your) mind)/],
    keywords: ["take back", "mahjong", "change", "mind"],
    answer:
      "No. Once you call mahjong and expose your tiles, the declaration stands. If it turns out your hand is not valid, it is treated as a false mahjong. Do not call mahjong until you are certain.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    related: ["false-mahjong", "valid-mahjong", "take-back-discard"],
  },
  {
    id: "passed-winning-tile",
    category: "winning",
    level: "core",
    question: "What if I passed my winning tile in the Charleston?",
    patterns: [/pass.{0,30}(winning|needed|need|good) tile/, /(winning|needed) tile.{0,30}pass/, /gave away.{0,20}tile/],
    keywords: ["pass", "winning", "tile", "charleston"],
    answer:
      "This happens! If you accidentally pass a tile you could have used to win, you can simply continue play. There is no penalty; you just do not have that tile anymore.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/winning`,
    related: ["charleston", "look-before-pass", "charleston-passes"],
  },
  {
    id: "pay-discard-win",
    category: "scoring",
    level: "advanced",
    question: "Who pays when someone wins on a discard?",
    patterns: [/who pay/, /\bpay\b.{0,30}(discard|call|thrower|threw|discarder)/, /(discard|discarder|thrower).{0,30}\bpay\b/, /pay double/, /how (much|does).{0,20}(discarder|thrower).{0,20}pay/],
    keywords: ["pay", "discard", "double", "who"],
    answer:
      "When a player wins by calling a discard, the player who discarded that tile pays twice the normal amount (they pay for themselves and double). The other two players each pay the standard single amount. This is the standard NMJL payment structure, though some groups play 'all pay'; confirm with your group.",
    varies_by_house: true,
    house_note: "Some groups play 'all pay'; confirm your table's payment rule.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/scoring`,
    related: ["pay-self-drawn", "joker-free", "game-value"],
  },
  {
    id: "pay-self-drawn",
    category: "scoring",
    level: "advanced",
    question: "Who pays on a self-drawn win?",
    patterns: [/\bpay\b.{0,30}self.?draw/, /self.?draw.{0,30}\bpay\b/, /\bpay\b.{0,30}(own|my) draw/],
    keywords: ["pay", "self", "draw"],
    answer:
      "On a self-drawn win, all three other players each pay the full amount. No one discarded the winning tile, so the cost is shared equally among all three losers.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/scoring`,
    related: ["pay-discard-win", "self-drawn-win", "joker-free"],
  },
  {
    id: "game-value",
    category: "scoring",
    level: "advanced",
    question: "How much is a hand worth?",
    patterns: [/how much.{0,20}(worth|bet|per hand|money|pay)/, /(game|hand) value/, /(cents|dollar|quarter).{0,30}(hand|game|point)/, /how (do|does).{0,20}(scoring|score|point).{0,20}work/],
    generic: [/(bet|stake|wager)/, /\bscor(e|ing)\b/],
    keywords: ["worth", "value", "bet", "score", "point"],
    answer:
      "The NMJL does not set a fixed dollar amount; groups agree on their own bet per hand before play begins. Common amounts range from 25 cents to $1 per point or per hand. Whatever your group agrees, that amount is what 'one unit' means for payment purposes.",
    varies_by_house: true,
    house_note: "The amount per hand is always a group agreement.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/scoring`,
    related: ["pay-discard-win", "joker-free", "extra-payments"],
  },
  {
    id: "extra-payments",
    category: "scoring",
    level: "advanced",
    question: "Do any hands pay extra beyond joker-free?",
    patterns: [/(extra|bonus|double|triple).{0,30}(hand|pay|quint|single)/, /(quint|single).{0,20}(hand).{0,20}(pay|worth|double)/, /pay (extra|more|double|triple)/],
    keywords: ["extra", "bonus", "double", "triple", "pay"],
    answer:
      "Some groups play that certain named hands (like Singles and Pairs or Quint hands) pay double or triple by house agreement. The NMJL card itself does not designate specific multipliers beyond the joker-free rule; any extra payments are house rules and should be agreed on before the game.",
    varies_by_house: true,
    house_note: "Any multiplier beyond joker-free is a house rule.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/scoring`,
    related: ["joker-free", "game-value", "pay-discard-win"],
  },
  {
    id: "take-back-discard",
    category: "etiquette",
    level: "core",
    question: "Can I take back a discard?",
    patterns: [/(take back|undo|retract|change (my|your) mind|pick back up|oops).{0,30}discard/, /discard.{0,30}(take back|undo|retract|change (my|your) mind|by mistake|accident)/, /(accident|mistake).{0,20}discard/],
    keywords: ["take back", "discard", "mistake", "accident"],
    answer:
      "No. Once a tile is placed face-up on the table as a discard, it cannot be taken back. The moment a tile is set down as a discard, other players may call it. Be certain before you discard.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/etiquette`,
    related: ["most-recent-discard", "change-mind-mahjong", "call-window"],
  },
  {
    id: "table-talk",
    category: "etiquette",
    level: "core",
    question: "What counts as table talk?",
    patterns: [/table talk/, /(talk|say|announce|tell).{0,30}(hand|need|looking for)/, /(hint|signal|comment).{0,30}(hand|discard|tile)/],
    keywords: ["talk", "table", "announce", "hint"],
    answer:
      "Table talk is any verbal communication that gives information about your hand or strategy to other players, or that influences how others play. Examples: announcing what you need, commenting on another player's discard choices, or reacting to tiles in a way that signals your hand. Table talk is generally prohibited in competitive play. In casual home games, groups set their own rules.",
    varies_by_house: true,
    house_note: "Casual groups set their own table talk rules; competitive play prohibits it.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/etiquette`,
    related: ["courtesies-vs-rules", "see-exposed-tiles", "disputes"],
  },
  {
    id: "call-window",
    category: "etiquette",
    level: "core",
    question: "How fast do I have to call a discard?",
    patterns: [/how (fast|quick|long|soon).{0,30}call/, /(window|time|too late|late).{0,30}call/, /call.{0,30}(too late|late|window|before the next|next player draw)/, /(next player|already) (draw|drew|picked)/],
    keywords: ["fast", "late", "window", "call", "draw"],
    answer:
      "You must call a tile before the next player draws from the wall. Once the next player has drawn, the window to call the previous discard is closed. There is no strict timer, but you should call promptly; hesitating too long is considered poor etiquette.",
    varies_by_house: true,
    house_note: "Tables differ on the exact moment the calling window closes; agree on it before you start.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/etiquette`,
    related: ["most-recent-discard", "calling-discard", "take-back-discard"],
  },
  {
    id: "disputes",
    category: "etiquette",
    level: "core",
    question: "Who resolves a rules dispute?",
    patterns: [/who (decide|is right|has the final)/, /can'?t agree/, /(settle|resolve).{0,20}(dispute|argument|disagreement|rule)/],
    generic: [/(dispute|argument|disagree|argue|fight|settle|resolve)/],
    keywords: ["dispute", "disagree", "resolve", "argue"],
    answer:
      "In a home game, all four players agree together (majority rules or unanimity, depending on the group). In a league or club setting, a designated rule referee or club leader makes the call. If no resolution is possible mid-game, the safest option is to replay the hand.",
    varies_by_house: true,
    house_note: "Each group decides how it settles disputes; agree on it before you play.",
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/etiquette`,
    related: ["house-vs-nmjl", "courtesies-vs-rules", "dead-hand-saved"],
  },
  {
    id: "see-exposed-tiles",
    category: "etiquette",
    level: "core",
    question: "Can I look at another player's exposed tiles?",
    patterns: [/(look|see|view|check).{0,30}(another|other|someone|opponent).{0,20}(expose|tile|rack)/, /(expose|tile).{0,20}(visible|public|private|hidden)/],
    keywords: ["look", "see", "exposed", "rack"],
    answer:
      "Yes. Exposed tiles (those placed face-up on the table after a call) are always visible and any player may look at them at any time. Concealed tiles in another player's rack are private.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/etiquette`,
    related: ["joker-exchange", "table-talk", "expose-immediately"],
  },
  {
    id: "house-vs-nmjl",
    category: "etiquette",
    level: "core",
    question: "What is the difference between a house rule and an NMJL rule?",
    patterns: [/house rule.{0,20}(vs|versus|and|or).{0,20}(nmjl|official|league)/, /(nmjl|official|league).{0,20}(vs|versus|and|or).{0,20}house/, /what is (a |an )?(house|nmjl|official) rule/, /is (this|that|it) (a |an )?(house|official|nmjl|real|standard) rule/],
    generic: [/\bnmjl\b/, /official/],
    keywords: ["house", "nmjl", "official", "league", "rule"],
    answer:
      "NMJL rules are the official rules published by the National Mah Jongg League and apply to all standard American Mahjong play. House rules are variations or additions agreed upon by a specific group that are not part of the official rules. House rules are fine for casual play; just make sure all players agree before the game starts. When in doubt about what is 'official,' the NMJL card and published guidelines are the authority.",
    varies_by_house: false,
    confidence: "high",
    source: "lvm_rules_page",
    source_url: `${RULES}/etiquette`,
    related: ["courtesies-vs-rules", "disputes", "annual-card"],
  },

  // ── Stitched from approved sentences (verbatim sentences, combined) ─────────
  {
    id: "called-dead",
    category: "dead-hands",
    level: "advanced",
    question: "What happens if someone calls me dead?",
    patterns: [/(call|called|declare|declared|say|says|said).{0,15}(me|my hand|i am|i'm|you|your hand).{0,10}dead/, /(someone|somebody|another player|they).{0,20}(call|declare).{0,20}dead/, /dead.{0,20}(challenge|accuse)/, /(challenge|accuse).{0,20}dead/],
    keywords: ["dead", "called", "challenge"],
    answer:
      "Calling another player's hand dead is a formal challenge, so be sure you are right before you make it. Once a hand is declared dead, that player does not draw or discard for the rest of the hand. They sit out until the next hand begins. A player whose hand is declared dead must still pay the winner if someone else wins.",
    varies_by_house: true,
    house_note: "Tables enforce dead hand challenges with different levels of strictness.",
    confidence: "medium",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-triggers", "dead-hand-saved", "disputes"],
  },
  {
    id: "wrong-exposure",
    category: "dead-hands",
    level: "advanced",
    question: "What happens if I expose the wrong tiles?",
    patterns: [/expose.{0,30}(wrong|incorrect|bad|mistake|by accident|accident)/, /(wrong|incorrect|bad|mistake).{0,30}expose/, /(wrong|incorrect).{0,20}(tile|set|group).{0,30}(table|down|out)/, /(put|lay|set) (down|out).{0,20}wrong/],
    keywords: ["expose", "wrong", "mistake", "incorrect"],
    answer:
      "Exposing tiles incorrectly is one of the things that makes a hand dead. If a player notices an error before other players have acted on it (before the next player draws), the group may agree to correct it. Once play has advanced past the error, the hand is typically dead. The key is catching it immediately.",
    varies_by_house: true,
    house_note: "Whether a group allows a correction is a table decision.",
    confidence: "medium",
    source: "lvm_rules_page",
    source_url: `${RULES}/dead-hands`,
    related: ["dead-hand-saved", "dead-hand-triggers", "expose-immediately"],
  },

  // ── Derived from approved statements; wording pending instructor review ────
  {
    id: "call-during-charleston",
    category: "charleston",
    level: "core",
    question: "Can I call a tile during the Charleston?",
    patterns: [/call.{0,40}(during|in|before).{0,10}charleston/, /\bcall\b.{0,50}\bcharleston\b/, /charleston.{0,40}call/, /call.{0,20}(pass|passed) tile/, /(pass|passed) tile.{0,20}call/],
    keywords: ["call", "charleston", "pass"],
    answer:
      "No. The Charleston is the tile passing that happens before play begins, and the first discard only happens after the Charleston, when East opens play. There are no discards during the Charleston, so there is nothing to call.",
    varies_by_house: false,
    confidence: "high",
    source: "derived",
    source_url: `${RULES}/charleston`,
    related: ["charleston", "calling-discard", "dealing"],
  },
  {
    id: "joker-in-news",
    category: "jokers",
    level: "core",
    question: "Can I use a joker in NEWS?",
    patterns: [/\bjoker\b.{0,40}\bnews\b/, /\bnews\b.{0,40}\bjoker\b/, /\bjoker\b.{0,30}\b(north|east|west|south)\b/, /\bwind\b.{0,30}\bjoker\b/],
    keywords: ["joker", "news", "wind"],
    answer:
      "No. NEWS is made up of four different tiles (North, East, West, and South), so each one counts as a single tile, and a joker can never be used as a single. Jokers only work inside groups of 3 or more identical tiles: a Pung, Kong, Quint, or Sextet.",
    varies_by_house: false,
    confidence: "high",
    source: "derived",
    source_url: `${RULES}/jokers`,
    related: ["joker-in-pair", "joker-single", "winds"],
  },
  {
    id: "discarded-joker",
    category: "jokers",
    level: "core",
    question: "Can I pick up a discarded joker?",
    patterns: [/(pick up|call|take|claim|grab).{0,30}(discard|thrown).{0,15}joker/, /joker.{0,20}(discard|thrown|on the table).{0,40}(pick|call|take|claim|grab)/, /discard.{0,15}joker/, /joker.{0,15}discard/],
    keywords: ["joker", "discard", "pick up", "call"],
    answer:
      "No. Once a joker is discarded it is out of play for the rest of the hand; no player may call it, not even for mahjong. The only way to take a joker from the table is a joker exchange from an exposed group on your own turn.",
    varies_by_house: false,
    confidence: "medium",
    source: "derived",
    source_url: `${RULES}/jokers`,
    related: ["joker-exchange", "calling-discard", "take-back-discard"],
  },
  {
    id: "call-for-pair",
    category: "calling",
    level: "core",
    question: "Can I call a tile to make a pair?",
    patterns: [/call.{0,30}\bpair\b/, /\bpair\b.{0,30}call/, /call.{0,20}(a )?single/],
    keywords: ["call", "pair", "single"],
    answer:
      "No. You may only call a discard for an exposed group of 3 or more identical tiles (a Pung, Kong, Quint, or Sextet), or when that tile completes your mahjong. A pair by itself cannot be called; the exception is when the pair is the last thing your hand needs, because then the call is for mahjong.",
    varies_by_house: false,
    confidence: "high",
    source: "derived",
    source_url: `${RULES}/calling-tiles`,
    related: ["calling-discard", "call-for-mahjong", "joker-in-pair"],
  },
];

export const KNOWLEDGE_BY_ID: ReadonlyMap<string, KnowledgeEntry> = new Map(
  RULES_KNOWLEDGE.map((e) => [e.id, e])
);
